# Jekyll configuration

name: Soma S Dhavala
description: A perspective on all things Data-Science

# url is currently only used only for the RSS feed in feed.xml
url: ''

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'dhavala'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: 'saddlepoint'

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate', jekyll-mentions, jekyll-feed, jekyll-sitemap, jekyll-gist]
jekyll-mentions:
    base_url: https://github.com

exclude: ['README.md', 'LICENSE', '_site']

collections:
  projects:
    output: true
  cv:
    output: true

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      title: posts
      is_collection: false # automatically set is_post=true for all any collection
      page_type: posts # htmls rendered by jekyll
      excerpt_separator: <!--more--> # exceprt for blogs

    scope:
      path: ""      # empty string for all files
      type: pages   # limit to collections
      title: posts
    values:
      is_collection: false # automatically set is_collection=true for all any collection
      page_type: pages # static htmls outside of _posts and are not rendered by jekyll
      excerpt_separator: <!--more--> # exceprt for blogs

    scope:
      path: ""      # empty string for all files
      type: drafts   # limit to collections
    values:
      title: drafts
      is_collection: false # automatically set is_collection=true for all any collection
      page_type: drafts # static htmls outside of _posts that are in staging
      excerpt_separator: <!--more--> # exceprt for blogs

    scope:
      path: ""      # empty string for all files
      type: projects   # limit to collections of projects
    values:
      title: Projects
      is_collection: true # automatically set is_collection=true for all any collection
      page_type: projects # useful in reading "project" specific variables
      excerpt_separator: <!--more--> # exceprt for blogs

    scope:
      path: ""      # empty string for all files
      type: cv   # limit to collections of projects
    values:
      title: Curriculum Vitae
      is_collection: true # automatically set is_collection=true for all any collection
      page_type: cv # useful in reading "cv" specific variables
      excerpt_separator: <!--more--> # exceprt for blogs

