---
title: "వద్దిపర్తి పద్మాకర్ గారి అష్టావధానం - హ్యూస్టన్ విశేషాలు"
description: "అవధాని - వద్దిపర్తి పద్మాకర్ (ఏలూరు) నిర్వహణ - శాయి రాచకొండ సభాధ్యక్షుడు - జె.వి. రమణమూర్తి"
author: "Soma S Dhavala"
date: "2010-07-28"
categories: ["telugu", "archive", "పద్యాలు"]
---

అవధాని - వద్దిపర్తి పద్మాకర్ (ఏలూరు)  
నిర్వహణ - శాయి రాచకొండ  
సభాధ్యక్షుడు - జె.వి. రమణమూర్తి  
శాలువ - ముత్యాల భాస్కర రావు  
సాంకేతిక సహకారం - రాం చెరువు  
వేదిక - అంజలి నాట్యకళాకేంద్రం, హ్యూస్టన్  
ప్రాయోజకులు - హ్యూస్టన్ తెలుగు సాంస్కృతిక సమితి (T.C.A - Houston)  
1. అప్రస్తుత ప్రసంగం - వంగూరి చిట్టెన్ రాజు  
2. సమస్య - మురళి అహోబిలవఝ్ఝల - ఉత్పలమాల  
రాముడు పార్వతీ తనయు డారయ సీత మహేశు పత్నియే  
శ్రీమహిళా శిరోమణి వరిష్ఠ విశిష్ఠ పదమ్ములంటి శో  
భామయ జీవితమ్మునకు వత్తురటంచునమ్మి నమ్మి సు  
త్రాముడు పార్వతీ తనయుడారయ సీత మహేషు పత్నియున్  
క్షేమము స్థే*మము కలుగ చెంతకుకుచేరి నమస్కరించరే  
3. దత్తపది -సోమశేఖర్ ధవళ [అది నేనే :)]  
అట్టు, ఇడ్లీ, పూరీ, ఉప్మా - ఈ పదాలను ఉపయోగిస్తూ, ముంబాయి మారణకాండకు కారకమైన తీవ్రవాదాన్ని గజేంద్ర మోక్షానికి అన్వయిస్తూ, లేదా జ్ఞప్తికి తెస్తూ, మత్తేభంలో ఘీంకారం చేయండి.  
కరమట్టుంగని*సనిట్టునూపుచును రాగద్వేష విభ్రాజిత  
స్ఫురణా సంపదగల్గి ఇడ్లిచిట ఉచ్చుందీయగా ఆజితో  
త్కరమున్ భారతభూమి జేయుటకు రాగా కష్టదుశ్శీలు ఘో  
రరణోర్వింబడ ప్రేమపూరితుడు సంరంక్షించు నుప్మాయనన్  
4. వర్ణన -మల్లిక్ పుచ్చా - స్వేచ్ఛా వృత్తం  
కేదార్నాధ్, హిమగిరి సొగసులు, రుద్ర వేద ఘోష, శంకర గానం, ప్రేక్షకుల తన్మయత్వం  
కేదారేశ పవిత్ర లింగమిట సూక్ష్మీభూతమై యొప్పగా వి  
ద్యాదీక్షా వర శీతలత్వ విమలత్వంబంది హ్యూస్టన్నులో  
కేదారాది సమస్త తీర్ధములు చూడబోనేల కా  
దా దక్షుల్ గల మంచిచోటిదియె తీర్థత్వంబునందింపగన్  
శార్దూలం (మ స జ స త త గ)  
5. న్యస్తాక్షరి - సత్యదేవ్ చిలుకూరి - మత్తకోకిల  
పెళ్లి అయిన మొదటి ఆషాఢ మాసం లో కోడలు పుట్టింటికి వెళ్ళడం ఆచారం. అత్తా కోడళ్ళు ఒక గడప దాటగూడదని నియమం. ఆ సమయంలో భార్యాభర్తల విరహ వేదన, మనోభావాలు వర్ణించండి  
ఒకటవ పాదం - రెండవ అక్షరం ఖ్య (ప్రాస)  
రెండవ పాదం - 13 పా  
మూడవ పాదం - 14 స  
నాల్గవ పాదం - 3 త్య  
సౌఖ్యముండునె నీవులేనిది సర్వలోకమహేశరా  
లేఖ్యమైనది నీదురూపమలేఖ్య పాలనశీలుడా  
ప్రఖ్యపొందిన శూన్యమాసము బాగుగోసమెకాదొకో  
మాఖ్యత్యక్తము చేయూకూడదెమాదు దంపతికోసమై  
6. నిషిద్దాక్షరి - సత్య పిళ్ళా - అన్నిపాదాలు - త వర్గం నిషిద్ధం  
ఇతివృత్తం - వర్గపోరాటలు మాని జాతి ఐక్యత యొక్క ఆవశ్యకతను తెలియజేస్తూ శాంతి సందేశం  
అవధాని ఉవాచ - ఇది ఎప్పుడూ కందంలోనే చెప్పాలి, స్వేచ్ఛా వృత్తం కూడదు  
కంద ఛందస్సు ప్రకారం, రెండు, నాల్గు పాదాల యందలి చివరి అక్షరం "న్" కావొచ్చు (త వర్గం నిషిద్ధమైనా గాని)  
శ్రీరమ్య విశాల యశో  
ఘోరమ్మగు రణము విడిగ కూడగ ప్రజయున్  
శ్రీరమ వాణియు ఐక్యము  
లో రంజిల్లరొకొ జగములో సుఖమొప్పన్  
7. ఆశువు - సుమన నూతలపాటి  
ఇతివృత్తం - 1) సమానత్వం అసమానత్వం 2) అంజలీ కార్యకలాపములపై 3) ప్రాణముల్ ఠావుల్ దప్పెను ని హనుమంతుడికి అన్వయిస్తూ  
8. పురాణం - సీతారాం అయ్యగారి  
* అనుమాన నివృత్తి చేసుకోవలసిన అక్షరాలు
