---
title: "Service"
description: "Service to the institute and to the wider research community."
---

> Asking “What can I get?” creates scarcity.
> Asking “What can I give?” creates abundance. 
> 
> -- Soma S. Dhavala


## IIT Jammu

*(To be added.)*

## Impact Sector
- Technical Expert, on Open Source AI, for _Digital Futures Lab_, 2025, [report](https://cdn.sanity.io/files/cfrp3y1m/production/aa01f2df2c804bbf462e58e9df763d86281a278b.pdf), [article](https://www.digitalfutureslab.in/publications/advancing-open-source-ai-in-india-recommendations-for-governments-and-technology-developers)
- Member, Working Group on Indic Voice Technologies for an Inclusive India, for _Digital Futures Lab_, 2026, [report](https://cdn.sanity.io/files/cfrp3y1m/production/5372f0e7d143fbaecf43ea107e428acad6d9add7.pdf), [article](https://www.digitalfutureslab.in/publications/publication-voice-technologies-for-indian-languages-best-practices-and-recommendations-for-responsible-and-open-ai)
- Mentor, Impact Fellowship Programme, _[ISDM](https://www.isdm.org.in/centre-for-data-science) Center for Data Science and Social Impact_, 2024-25




## Government
- Steering Committee Member, AI Cell, Dept. of IT, Govt. of Jammu and Kashmir
- Member, Advisory Board, Real Time Governance, Govt. of Andhra Pradesh



## Profession

- Reviewer, UAI 2026
- Reviewer, CODS 2025
- Executive Committee Member: IEEE Computer Society, Bangalore Chapter,  2019
- Reviewer, Bayesian Analysis, JASA, Integrative Biology, 2010-14
- Treasurer, ASA South East Texas Chapter, 2008-10
- Judge, Student Research Week, TAMU, 2008

## Community

- Part-time Tutor — Purna Pramati, Bengaluru, 2018–2019
- Treasurer — Carnatic Music Association of Indianapolis, 2013–14\
  Coordinated fundraising and music-event management, ran newsletter campaigns, and managed budgets and balance sheets.
- Student Advisor — CRY, TAMU chapter, 2007–08\
  Mentored the student-chapter executive body in organizing fundraising and event management.
- President — CRY, TAMU chapter, 2006–07\
  Organized fundraising events and awareness campaigns.
- Volunteer — SPICMACAY, TAMU chapter, 2005–09\
  Organized fundraising events, managed artist hospitality, and ran video campaigns.
- Volunteer — Association for India's Development, TAMU chapter, 2006–07\
  Helped with AID fundraising events and created awareness videos.
- Volunteer — India Students Association, TAMU chapter, 2006–07\
  Facilitated on-boarding and assimilation of new Indian graduate students.
- Volunteer — SANKALP, ISU, 2003–05\
  Participated in fundraising drives.
