---
title: "మన గురివిందగింజ నలుపే సుమా!"
description: "స్లమ్ డాగ్ మిలియనీర్ (SM). దీని మీద జరుగుతున్న చర్చ ఇంతా అంతా కాదు. మచ్చుకి కొన్ని కౌముదిలో గొల్లపూడిగారు"
author: "Soma S Dhavala"
date: "2009-02-28"
categories: ["telugu", "archive", "సినీమా"]
---

స్లమ్ డాగ్ మిలియనీర్ (SM). దీని మీద జరుగుతున్న చర్చ ఇంతా అంతా కాదు. మచ్చుకి కొన్ని  
కౌముదిలో గొల్లపూడిగారు  
దానిపై వారి వివరణ  
*** వాళ్ళకి లేవా మనోభావాలు (నవతరంగం)  
*** రావు గారి వువాచ (e-కలం)  
విజయేంద్రవర్మ -SM (జీడిపప్పు)  
ఎందుకు అన్నిఅవార్డులు (జీడిపప్పు)  
మురికివాడల *** (గుంపులోగోవిందం)  
మురికివాడల *** (అబ్రకదబ్ర)  
*** మీ గురివిందగింజ తెలుపా **? (అంతర్యానం)  
సైమన్ బఫాయ్ (స్వంత మాటల్లొ)  
వాటిలో వచ్చిన కామెంట్లుతో కలిపిచూస్తే ... ఈ సినిమా మీద విమర్శలకన్నా, దీన్ని విమర్శించినవాళ్ళ మీద విమర్శలే తీవ్రంగా ఉన్నాయి. ముఖ్యంగా మనతెలుగువారైన "గొల్లపూడి" గారి మీద.  
ముందు సినిమా గురించి నా అభిప్రాయం (నవతరంగంలొ చెప్పిన విషయాన్ని ఇక్కడ కొంచం విశదీకరించి రాస్తున్నాను). సినిమాని సమీక్షించే ముందు, దాన్ని మూడు భాగాలుగా చేద్దాం.  
1) taking/making (కధనం, సాంకేతిక విలువలు, ప్రయత్నం, పడ్డ కష్టాలు వగైరా)  
2) presentation (ప్రచారం, సమర్పించిన విధానం)  
౩) content (కథ)  
taking/making విషయానికి వస్తే, నాకు చాలా నచ్చిన సినిమా. ఉదాహరణకి, సినిమా మొదట్లో మురికివాడల్లోని chasing scene. వెనకాల డప్పులు మ్రోగుతుంటే, కదనరంగంలో సైనికులవీరంగం మల్లే ఉంది. సైమన్ బఫాయ్ వ్యాసం చదివితే దీని నేపధ్యం అర్ధమవుతుంది. సినిమా ఆద్యంతం పట్టుసడలకుండా intense గా సాగుతుంది. మురికివాడల, ధనికవర్గాలవారి జీవినవిధానంలోని వ్యత్యాసము చూపడంలో దర్శక-సాంకేతికనిపుణులు కృతకుత్యులయ్యారు. నేపధ్యసంగీతం, చాయాగ్రహణం మొదలైనవి సినిమా విజయవంతమవ్వడనికి దోహదపడ్డయి. Curious case of Benjamin Button తో పోలిస్తే, దీనిక Oscars రావడంలో వింతేమీ లేదు. అందుకు, దర్శక-నిర్మాతలకీ, సాంకేతికవర్గానికి అభినందనలు.  
సినిమా Title ని ఎన్నుకోవడంలోనే నిర్మాతల (లేదా/మరియు దానికి భాద్యులైన వారి) వ్యాపారాత్మక ప్రతిభ కనబడుతుంది. భారతదేశం, పేదరికం, ప్రేమ, ఆశ, మొక్కవోని ఆత్మవిశ్వాసం, డబ్బు. వీటిని Q&A అనే రుబ్బురోలు లోవేసి రుబ్బండి, అలా వచ్చిన కాకా హోటలు పచ్చడిని, ఎదురుకుండాఉన్న అయిదునక్షత్రాల హోటలులో ఆరగించండి. బ్రేవ్ మని త్రేన్చుతూ, పొట్టనిమురుకొనేట్లుగా చెయ్యడంలో వారి ప్రతిభ మరోసారి కనబడుతుంది. దీన్నుంచి మనవాళ్ళు నేర్చుకోవాల్సింది ఎంతైనా ఉంది.  
ఇక చివరిగా, కథగురించి. ఎంతోమంది అనుకొంటున్నట్టుగా ఇదొక ఆశావహుడైన ఒక మురికివాడజీవి ప్రయాణంలా నాకస్సలు అనిపించలేదు. చిన్నతనంలో, జమాల్, అతను స్నేహితులు, ఆశావాదులుగా కాదు, అవకాశవాదులుగా కనబడ్డారు. దీనికి నా చిన్నప్పుడు జరిన ఒకసంఘటన చెప్తాను. నాకప్పుడు ఒక 5-6 ఏళ్ళు ఉంటాయి. కాబోలు . మా ఇంటికి ఒక రెండువీధులవెనక కొంచం మురుకివాడల్ని పోలిన గడపలు ఉండేవి. రధాయాత్రరోజులు అనుకుంటా, ఒక గాలిపటం పావలాపెట్టి కొనుక్కుని, ఇంటిముందు వీధిలో, దానికిదారంకట్టి ఎగరెయ్యడానికి నానా అవస్థపడుతుంటే, నాఅంతవయసే ఉన్న మరో కుఱ్ఱాడు, నువ్వు దారం పట్టుకో, నేను గాలిపటంపట్టుకొని, పరిగెడతాను అప్పుడు ఎగురుతుంది అనిసంజ్ఞలతోనే చెప్పి, కాసేపు పరిగెట్టి, దారంతెంచి, గాలిపటంపట్టుకొని పారిపోయి ఆ మురికివాడాలో తేలాడు. కాసేపు నేను చేష్టలుడిగి అలా ఉండిపోయాను. ఆ కుఱ్ఱాడి ప్రతిరూపమే నాకు ఈ జమాల్ & కో లో కనిపించింది. ఎలాగైనా సాధించాలి అనే పట్టుదల మంచిదే! ఒక పావలా సంపాదించి గాలిపటంకొనుక్కొని ఎగరెయ్యడం, అభినందనీయం. గాలిపటంలాక్కుని పొందటం అభిశంసనీయం. SM లో నాకు గోచరించినది రెండోదే!  
ఒక్కసారి chasing scene ని జ్ఞప్తికి తెచ్చుకుంటే: సముద్రంలోని అలలు మైలు దూరంనుంచి మొదలయ్యి, తమతో భూమండలాన్ని మింగడనికా అన్నట్లు, ఒకదాని వెంట ఒకటి తరుముకుంటూ వస్తాయి. కానీ కబళించడం తమవల్ల సాధ్యంకాదూ అని తెలిసికాబోలు, ఒడ్డుని ధబ్బుమనిఢీకొని మరొకసారి నీ పనిపడాతానని ఉస్సూరుమంటూ వెనుదిరుగుతాయి. ఆ పోలీసు పర్సిస్థితీ అంతే! ఒక అయిదు నిముషాలు chase చేసినా ప్రయోజనం ఉండదని తెలుసు. కానీ chase చేస్తాడు. chasing scene అధ్బుతంగా తెరెకెక్కించారు. action సరే! మరి దానికి ముగింపేదీ. ఇక్కడే నాకు దర్శకుడి intention మీద అపనమ్మకం కలిగింది. అవకాశవాదం/మురికివాడాల మలినాన్ని destiny,/hope అనే wrapper లో చుట్టిఇచ్చినట్టుగా ఉంది. ఇంక జమాల్ ప్రేమ వయహారమా! బాలీవుడ్ సినిమాలు చూసి, చూసి, రవ్వంతకూడా ఆశ్వాదించలేదు.  
అందుకే నా దృష్టిలో ఇది  
మామూలు సినిమాల్లో గొప్పసినిమా గొప్పసినిమాల్లో మామూలు సినిమా  
ఇక విమర్శలగురించి: చాలావరకు వస్తున్న విమర్శలు కధగురించి, దాన్ని చూపించిన విధానం గురించి. అసలు పేదరికాన్ని చూపించాలా వద్దా, చూపిస్తే ఎలే చూపించాలి. పెంట కుప్పలో ములగాలా? అఖ్ఖర్లేదా? ఇత్యాదులు. సినిమా మాధ్యమంలోని చిత్రమేమిటంటే, చూసిన/చూడని ప్రతీఒక్కడు, ఇలా తియ్యాలి, ఇలాగే తియ్యాలి అనుక్కోవడం (తీసిన అనుభవం ఉన్నా లేకున్నా, సాదకబాధకాలు తెలిసినా తెలియకున్నా), అదే సరియనది అని నమ్మడం. దీనికి ఎవరూ అతీతులు కాదు. ఒకే సన్నివేసాన్ని చూసి, సంధర్బం బట్టి, ఒకే వ్యక్తి పలు రకాలుగా స్పందిస్తాడు. మరి పలు వ్యక్తులు రకాలుగా స్పందించడంలో ఆశ్చర్యమేముంది. విమర్శకులందరూ విచిత్రంగా దీన్ని విస్మరిస్తారు. ఇదేమి లెఖ్కలు కాదు కదా 1+1 = 2 అని ఋజువుచెయ్యాడానికి. ఇక్కడే సినిమాని విమర్శించిన వాళ్ళు, సమర్ధించిన వాళ్ళు విభేదిస్తున్నారు అని నా అభిప్రాయం.  
ఇకగొల్లపూడి విమర్శ, దానిపై విమర్శల విషయానికివస్తే:  
నాకు ఆయన విశ్లేషణ చాలా సమంజసంగా కనిపంచింది. మొదట ఆయన "నాకు కళ అంటే ఫలానా, ఫలానా. నేను ఇలా నిర్వచిస్తాను. ఏ విధంగా ఉండాలి, ఉండకూడదు" అని ఒక సిద్ధాంతమేదో ప్రతిపాదించేరు. కొన్ని ఉదాహరణలు ఇచ్చేరు. దానికి లోబడి, SM లేదు. కాబట్టి నాకు నచ్చలేదు. అందుకే నేను చూడను అన్నారు. ఇందులో తప్పేంటి?  
నేను దశాంశమానంలోంచి చూశాను 1+1 =0 కాబట్టి తప్పు అని రావు గారు అంటే, అయ్యా మీకు బుర్ర లేదండీ, మీ మూర్ఖత్వంకాకపోతేనూ, నేను పెట్టుకున్న radix-2 కళ్ళజోడు పెట్టుకొని చూడండి, 1+1=0 సరియేను అంటే? ఇక్కడా ఎవరి కళ్ళాజోళ్ళు వాళ్ళవి! ఒకళి జోళ్ళు ఒకరికి నప్పవు మరి.  
ఒకరు, "అసలు మీరు కళకి ఎలా నిర్వచనం ఇస్తారు. ఏ సూత్రం లేకపోవడమే అసలైన సూత్రం," అంటారు. వినడానికి ఇది చాలా బావుంది. కొంతమేర నిజమే కూడా. నా దృష్టిలో అర్ధవంతమైన వాదన. కాని, కాంతికన్నా వేగంగా ప్రయాణించి, నక్షత్రాలకావల పాలపుంతలవింతలు చూసిరావడం ఎంత ఆచరణ యోగ్యమో, ఏ సూత్రమూ లేకుండా సినిమా నిర్మించడమూ, అంతే ఆచరణయోగ్యం. ఎంత కళాకారుడైన, సంపూర్ణ స్వాతంత్ర్యాన్ని వ్యాపారాత్మక ప్రపంచంలో అనుభవించలేడు.  
వీటన్నికి మించి, అసలు ఆయన సినిమానే చూడలేదు. ఆయనకి విమర్శించే హక్కు ఎక్కడిది అని కొందరు. నేను చూసిన జనాలలో, ఎక్కువమంది, ఇదే విషయం పదే పదే ప్రస్తావించారు. అందుకు వాడిన కొన్ని పదాలు:  
చెప్పుడు మాటలు విని, ఎవరో చెప్తే, విని, మూర్ఖత్వం, మట్టి మషాణం, మొదలైనవి  
అలా ఆడిగిన వాళ్ళందరు గమనించాల్సింది, అక్కడ చెప్పింది కొడుకు, విన్నది తండ్రి. కొడుకు, "నాన్నా సినిమా బావులేదు, ఇదిగో ఇలా చూపించారు, ఇలా ఉంది" అంటే, ఆ తండ్రి, కొడుకు మాటలు విశ్వసించకూడదా? ఆదే రంగంలో ఉన్న తండ్రి ఆ విషయాన్ని గ్రహించలేరా? పోనీ మనకా విషయం తెలియనప్పుడు, సంశయనివృత్తి కోరవచ్చునుకదా! కోరలేని పక్షంలో సంయమనం పాటించవచ్చుకదా?  
అసలు వాళ్ళబ్బాయి, సినిమా హాల్లొ సినిమా చూడాలేదు, DVD లో చూసాట్ట. piracy కాదూ!  
మీరు ముసిలివారైపొయారు ఇంక విశ్రాంతి తీసుకోండీ  
మీరు మీ అబ్బాయి పేరు మీద నెలకొల్పిన award ని వనజ కి ఇచ్చారు, అందులో ఇంకా జుగుప్సకరమైన ఘటనలున్నాయి. దానికిలేని అభ్యంతరం దీనికెందుకు? ఫలానా సినిమాలో ఇలాంటి పాత్రవేసారే? మీరూ విమర్శించేవాళ్ళేనా!  
ఇవన్నీ కాదుగానీ, అసలు సినిమా తీసినవాడు విదేశీయుడండి, అందుకేనండీ మీ ఆక్రోశం, ఆవేదనానూ!  
మనదేశీయుడు తీసిన సినిమాలో ఇంకా జుగుప్సాకరమైన ఘతనలు ఉన్నాయి. వాటిని ఎందుకు విమర్శించలేదు?  
మీ విమర్శ, దర్శక-నిర్మాతల విజ్ఞతని కించపరిచేదిగా ఉందండీ!  
అసలు విమర్శించే అర్హత మీకు లేదండీ!  
ఇవి మరికొంతమంది వ్యక్తపరచిన (యధాతధం కాకపోయినా,భావం మాత్రం అదే) అభ్యంతరాలు. ఎంతసంధర్భోచితంగా ఉన్నాయో అవి మీ విజ్ఞ్తతకే వదిలేస్తున్నాను.  
ఒక్క కొత్తపాళీ గారు మాత్రం "అభిరుచుల విషయంలో ఎవరి అభిప్రాయాలు వారివి. కాదనను. వేరే దృక్పథాన్ని మీతో పంచుకోవాలని మాత్రమే ఈ జాబు, పెద్దలతో వాదంఇచాలని కాదు" అంటూ హుందాగా వ్యవహరించేరు/విభేదించేరు.  
మనం ఆచరించలేని, అనుసరించలేని పరిపూర్ణస్వచ్చతని, అవతలి వ్యక్తిలో ఉండాలనుకోవడం, మనగురివిందగింజలోలేనితెలుపు అవతలి వ్యక్తిలో ఉండాలి అనుకోవడమే!  
చివరిగా  
"దీని [SM] దెబ్బకి రేపు రోడ్లమీద అమెరికన్లు నన్నేదో చులకనగా చూస్తారనుకునే న్యూనతా భావం నాకు లేదు. ఒక వేళ వాళ్లలా చూసినా, who cares? " అని అనగలిగిన ఆత్మవిశ్వాసం  
"I am entitled to my space to differ" అన్న గొల్లపూడి గారి అభిప్రాయాన్ని, దాంతో పాటు మన విజ్ఞ్తతని, వివేవచని మ్రింగేసే అహంకారం/అహంభావం గా మారకూడదనే నేను కోరుకునేది!  
గమనిక: అసలు నాకు పైన ప్రస్తావించబడిన బ్లాగర్లు పరిచయంలేదు. అలాగే గొల్లపూడి గారు కూడా. నిష్పాక్షికంగానే వ్యవహరించానని అనుకుంటున్నా. కొన్ని టపాలని verbatim quote చేసినా, అది వ్యక్తిగతంకాదని, సాధారణ భావజాలానికి ప్రాతిపదికగా మాత్రమే వాడ్డం జరిగిందని మనవి (అందుకే పేర్లు ఉటంకించలేదు). ఎంతోమంది కామెంట్లని ప్రస్తావించేను. అందరిని పేరు పేరునా quote చెయ్యడానికి బద్దకం :)  
మరోగమనిక: ఒకొక్కసారి, అసలు ఈ వాదనలలో అర్ధమేలేదనిపిస్తుంది. రాద్దాం అనుకుంటూ, మనం చెప్పేది మనకే వర్తిస్తుంది కదా అని మానేస్తాను (circular reasoning). SM విషయంలో కూడా అనుకుంటుండగానే,  
దూల ఎక్కువై,  
ఇదిగో ఇగోల గోల  
ఈలోగా ఇలాగ :)
