---
title: "ఆటవెలది లో మొదటిపద్యం"
description: "నేనింతవరకూ ఛందోబద్ధంగా ఎప్పుడూ రాయలేదు. నాకు ఎప్పటినుంచో ఈ కోరిక తీరని కోరికలాగే ఉండిపోయింది. ఆంధ్రామృతం వారు ఆశువుగా పద్యాలు చెప్పడం చూసి, స్ఫూర్తిపొంది ఈ ప్రయత్నం చే..."
author: "Soma S Dhavala"
date: "2009-01-15"
categories: ["telugu", "archive", "పద్యాలు"]
---

నేనింతవరకూ ఛందోబద్ధంగా ఎప్పుడూ రాయలేదు. నాకు ఎప్పటినుంచో ఈ కోరిక తీరని కోరికలాగే ఉండిపోయింది. ఆంధ్రామృతం వారు ఆశువుగా పద్యాలు చెప్పడం చూసి, స్ఫూర్తిపొంది ఈ ప్రయత్నం చేస్తున్నాను.  
ఆటవెలది:  
జఱభి నవ్వినంత, జాణతనంబంత  
నెఱగి జాబిలి, విటునె మరపించె  
ఉత్పలాక్షి గాంచి ఊసులుబోయెనా  
వన్నె, విరిసి మెరిసి వెన్నెలగుచు  
ఆటవెలది ఓ చిన్ననవ్వు విసరగానే, అందులోని జాణతనమంతా గ్రహించినా చందురుడు, రసికాగ్రేసరుడైన విటుడినే మరపించేడు. కలువల వంటి కన్నులుకల ఆ జవ్వనాంగిని చూడగానే, కలువలరేని వన్నెలు, చిన్నెలు, వెన్నలగ మారి విరిసేయి, మెరిసేయి.  
పద్యం ఎన్నోరూపాంతరాలుచెంది ఆవిధంగా వచ్చింది. ఎన్నిమార్పులు, చేర్పులూ జరిగేయి, పద్యంరాయడంలో పడ్డపాట్లు గురించి తెలుసుకోవాలంటే ....  
ఎలా అనేది క్రింద వివరించాను చూడండి.  
ముందు రాసింది ఇది:  
ఉత్పలాక్షిన్ గాంచిన, శశి ఉష సొగసుల  
వన్నె, వెన్నెలందు విరిసె, మెరిసె  
జఱభి నవ్విన, జాబిలి చెక్కిలి, చికి  
లించిన చెలియ కలల కనుబొమ్మ  
భావం:  
కలువల వంటి కన్నులు గల చిన్నాదాన్ని చూసిన కలువలరేని (చంద్రుని) కాంతుల సొగసులు వెన్నెలలో విరిసి, మెరిసేయిట. ఆ సుందరాంగి నవ్వితే, చంద్రుడి బుగ్గలు, ఆమె అందమైన కనుబొమ్మల్లా బాణంవంగినట్టు సొట్టబోయాయిట.  
ఆటవెలది లక్షణాలు:  
1) ఒకటి, మూడు పాదాల్లో రెండు ఇంద్రగణాలు, మూడు సూర్య గణాలు ఉండాలి  
2) రెండు, నాలుగు పాదాల్లో అయిదు సూర్య గణాలు ఉండాలి  
3) ప్రతీ పాదంలో మొదటి అక్షరం, నాల్గవ గణంలో మొదటి అక్షరం తో "యతిమైత్రి" ఉండాలి.  
వీటిని ఆధారంగా రాసిని పద్యాన్ని చూద్దాం:  
మొదటి పాదం గణ విభజన:  
(btw, U అంటే గురువు, I అంటే లఘువు)  
- ఉత్పలాక్షిన్(UIUU) గాంచిన(UII), శశి(II) ఉష(II) సొగసుల(IIII)  
- కలిపిరాస్తే UIUUUIIIIIIIIII  
- గణాలుగా విభజిస్తే UIU, UUI, III, III, III  
- అవివరుసగా ర, త, న, న, న  
- ర, త లు ఇంద్రగణాలు, న సూర్య గణం  
- ఊ, ఉ లు యతిమైత్రి కలిగిఉన్నాయ  
రెండవ పాదం గణ విభజన:  
- వన్నె(UI), వెన్నె(UI) లందు(UI) విరిసి(III), మెరిసె(III)  
- కలిపిరాస్తే UIUIUIIIIIII  
- గణాలుగా విభజిస్తే UI, UI, UI, III, III  
- అవిఅన్నీ గలము, గలము, , గలము న, న (, గలము అంటే "గురువు+లఘువు"అని)  
- "గలము", "న" ఇవి మాత్రమే సూర్య గణాలు  
- వ, వి లు యతిమైత్రి కలిగిఉన్నాయ  
మూడా పాదం గణ విభజన:  
- జఱభి(III) నవ్విన(UII), జాబిలి(UII) చెక్కిలి(UII), చికి(II)  
- కలిపిరాస్తే IIIUIIUIIUIIII  
- గణాలుగా విభజిస్తే III, UII, UII, UI, III  
- అవిఅన్నీ న,భ, భ, గలము, న, గణాలు  
- "గలము", "న" ఇవి మాత్రమే సూర్య గణాలు, మిగతావి ఇంద్రగణాలు  
- జ, చె లు యతిమైత్రి కలిగిఉన్నాయ  
నాల్గవ పాదం గణ విభజన:  
- లించిన(UII) చెలియ(III) కలల(III) కనుబొమ్మ(IIUI)  
- కలిపిరాస్తే UIIIIIIIIIIUI  
- గణాలుగా విభజిస్తే UI, III, III, III, UI  
- అవిఅన్నీ "గలము", న, న, న, "గలము", గణాలు  
- "గలము", "న" ఇవి మాత్రమే సూర్య గణాలు  
- లి, ల యతిమైత్రి కలిగిఉన్నాయ  
కాని:  
పెద్దలు చింతా రామకృష్ణారావు గారు, నరహరి గారు, రాఘవ గారు, , చదువరి గారు కొన్ని తప్పులు పట్టేరు వారికి నా కృతజ్ఞతలు.  
అవి:  
1) ఆ.వె లో మొదటి, మూడు పాదాల్లో 3 సూర్యగణాలు, 2 ఇంద్రగణాలు వరసగా రావాలి. నేను మొదటి రాసినదాంట్లో, ordering లేదు.  
2) ఆ.వె లో యతిప్రాస కుదురుతుంది. ఇంతకుముందు ఈ విషయంనాకు తెలియదు.  
పై రెండు సూచనలనీ పరిగణన లోకి తీసుకొని, ముందు రాసిన పద్యాన్ని ఈ విధంగా మారిస్తే,  
జఱభి నవ్వినంత, జాణతనంబంత  
నెఱగి జాబిలి, విటుని మరపించె  
ఉత్పలాక్షిని గనినంత, పున్నమిరేని  
వన్నె, విరిసె మెరిసె వెన్నెలగుచు  
వచ్చింది. మీరు గమనిస్తే, మొదటి రెండు పాదాల్లోనూ, యతి, చివరి రెండు పాదాల్లో ప్రాసయతి కి ప్రయత్నించినట్టు తెలుస్తుంది. కానీ, ఇందులో కూడ తప్పులు ఉన్నాయి. ఆచార్యులు చింతా రామకృష్ణారావు ఎంతో వ్యయప్రయాసలకోర్చి, సవివివరంగా comments ద్వారా తెలియజెప్పేరు. వారు సూచించినవిధంగా రెండో పాదంలోను, మూడోపాదంలోనూ యతిని సరిచేస్తే వచ్చినది:  
జఱభి నవ్వినంత, జాణతనంబంత  
నెఱగి జాబిలి, విటునె మరపించె  
ఉత్పలాక్షి గాంచి ఊసులుబోయనా  
వన్నె, విరిసి మెరిసి వెన్నెలగుచు  
నేను పైనవ్యక్తపరచినవి ఒక చిన్న పుస్తకం చూసి నేరుచుకుని, extrapolate చేసినవి. నాకు వీటిమీద పెద్దగా జ్ఞానంలేదు. పదోతరగతి వరకు కొంచం తెలుగు వ్యాకరణం చదువుకొన్నాను. ఉత్పలమాల, చంపకమాల, మత్తేభం, శార్ధూలం ఇవి మాత్రమే చదివినట్టుగుర్తు. అవిమరచిపోయి దశాబ్దంపైగాకావస్తోంది. అందుకే, ఒక వ్యాకరణ పుస్తకం ముందు పెట్టుకొని, కొంచం practice చేసాను. తెలిసిన పద్యానికి, గణవిభజన వగైరాలని. పద్యం ఇస్తే, అది కోవలోకి వస్తుందోచెప్పడం వరకూ పర్వాలేదు, కానీ, సూత్రాలని అనుసరిస్తూ రాయడం మాటలు కాదు అని తెలిసుకున్నాను. అప్పుడు, మన కవులమీదా అమాంతం గౌరవభావం, ఆరాధ్యనాభావాం ఉన్నదానికి ఒక వెయ్యిరెట్లు పెరిగాయనడంలో ఏ మాత్రం అతిశయోక్తిలేదు.  
నేను పైన రాసిన నాలుగు పదాలు చాలా వరకు trial & error తరువాత వచ్చినవి. ఎలాఅంటే:  
స్థూలంగా ముందు ఒక భావంకొని, rough draft తయారుచేసి, లఘువులుగా, గురువులుగా, విభజించి, గణాలు గుర్తించాలి. తరువాత అవి ప్రాధమిక సూత్రాలకి అణుగుణంగా ఉన్నాయోలేదో చూసుకోవాలి. అలా లేకపోతే నానార్ధాలో, పర్యాయపదాలో వాడడం, లేదూ అంటే వ్యాక్యాన్ని direct/indirect speech, active/passive voice లాగ మార్చడం, ఇంకా కుదరకపోతే, కొంచం భావమార్చడం చెయ్యాలి. నామటుకు, ఇదొక maths puzzle లా అనిపించింది. ఆటవెలది లో, ఉండాల్సినవి సూర్యగణలు (మొత్తం 2), ఇంద్రగణాలు(మొత్తం 16). గణవిభజన (parsing) ఎలాగైనా చెయ్యొచ్చు (మొత్తం 5 గణాలు ఉండేలా చూసుకోవాలి). కాబట్టి చాలా freedom ఉంది. ముందు ఒక రెండు పదాలు, చివర పదం అనుక్కొని, మధ్యలో ఏఏ పదాలు పడతాయో permutations ద్వారా ప్రయత్నించొచ్చు. ఇవి నేను try చేసిన methods. కావునా, handle with care :)  
ps: వ్యాకరణం, ఛందస్సు తెలిసినవారు ఇందులో ఏవైనా తప్పులుంటే సరిదిద్దగలరు.
