---
title: "బేరుమనేడ్వగలన్ కృపాకరో"
description: "వృత్తం రాయాలంటే, అమ్మో అంత పెద్ద పద్యం ఎలారాయగలం అని ఒక భయం ఉన్నాది (ఉండేది). అప్పుడొచ్చిన ప్రశ్నలు:"
author: "Soma S Dhavala"
date: "2010-08-20"
categories: ["telugu", "archive", "పద్యాలు"]
---

వృత్తం రాయాలంటే, అమ్మో అంత పెద్ద పద్యం ఎలారాయగలం అని ఒక భయం ఉన్నాది (ఉండేది). అప్పుడొచ్చిన ప్రశ్నలు:  
- వృత్తాల్ని ఎందుకు కుదించకూడదు  
- భరనభభరవ, ఈ వరుస క్రమాన్నే ఎందుకు ఎంచుకున్నారు, ఎలా ఎన్నుకున్నారు.  
- సంగీతంలో కొత్త రాగాలు కనుక్కుంటున్నారు. మరి ఛందస్సులో కూడా కొత్త వృత్తాలో, జాతులో, మరో వర్గాన్నో తయారుచెయ్యలేమే. చెయ్యాలంటే, దానికి పద్ధతి అంటూ ఏమైనా ఉందా?  
ఉదాహరణకి, ఉత్పలమాల తీసుకొంటే:  
భ ర న భ భ ర వ  
U I I U I U I I I U I I U I I U I U I U  
తానన తాన తా న తన తానన తానన తాన తా న తా  
సరిగ్గా యతి స్థానం దగ్గర విడగొడితే,  
భ ర న  
భ భ ర వ  
వీటితో, ఒక కందం, ఆటవెలది "లాంటి" పద్యాల్ని తయారుచెయ్యొచ్చు. ఇంకొంచం విశదీకరిస్తే, ఈ క్రింది సూత్రాలు తీసుకోవచ్చు  
1 వ పాదం: భ ర న  
2 వ పాదం: భ భ ర వ  
3 వ పాదం: భ ర న  
4 వ పాదం: భ భ ర వ  
1-2 పాదాలు సంయుక్తంగా, అలాగే ౩-4 కలిపి ఉత్పలమాల నియమాలు పాటించాలి. అంటే  
1 వ పాదం మొదటి అక్షరానికి, 2 పాదం మొదటి అక్షరానికి యతి-మైత్రి ఉండాలి.  
౩ వ పాదం మొదటి అక్షరానికి, 4 వపాదం మొదటి అక్షరానికి యతి-మైత్రి ఉండాలి.  
1 వ పాదం మొదటి అక్షరానికి, ౩ పాదం కి ప్రాస నియమం వర్తిస్తుంది.  
ఇప్పుడు మరిన్ని ఆంక్షలు విధించొచ్చు, ఎలా అంటే  
2 వ పాదం మొదటి అక్షరానికి, ఆందులో ౩ వ గణం మొదటి అక్షరానికి యతి-మైత్రి ఉండాలి (కందం లో లాగ)  
4 వ పాదం మొదటి అక్షరానికి, ఆందులో ౩ వ గణం మొదటి అక్షరానికి యతి-మైత్రి ఉండాలి (కందం లో లాగ)  
మరి కొంచెం బిగిస్తే  
ప్రాస నియమం పాటించడం  
ఈ నియమాలు పాటిస్తే, ఉత్పలమాల లోని, మొదటి రెండు, చివరి రెండు పాదాలు, వాటంతట అవే, "కందంలాంటి" పద్యాల్లాగ కనిపిస్తాయి. ఆ రకంగా ఆంక్షలతో కూడిన ఒక లఘువృత్తం తయరవుతుంది.  
కనీసం ఇలా ఆలోచించడం వలన, ఒక ఉత్పలమాల పద్యాన్ని రాయగలిగాను. ఇదే నా మొదటి ఉత్పలమాల.  
ఉ||  
వృత్తము వ్రాయగన్ జడిసి వేరొక మార్గము లేకనే కదా,  
చిత్తము పోరగన్, వగచి, చెత్తగ వృత్తము గీసితిన్, చఛా!  
బెత్తము తీయకండి మరి బేరుమనేడ్వగలన్. కృపాకరా,  
విత్తము నాటితిన్ ఇపుడె, విత్తులు, రూకలు సేకరించగాన్!  
తప్పులు దొరకనంత వరకూ ఇది ఉత్పలమాలే. దొరికితే ఛ.లే.ప అవుంతుంది. :)
