---
title: "మరపురాని మొదటి, \"పెళ్ళివీడియో\""
description: "విరామాన్ని జాగ్రత్తగా గమనించండి. \"మొదటి, పెళ్ళివీడియో\". \"మొదటి పెళ్ళి\" - వీడియో కాదు :). యూట్యూబ్ ఇంకా ప్రపంచానికి \"పూర్తిగా\" తెలియనప్పుడె మా వీడియో వికారం మొదలైంది. అ..."
author: "Soma S Dhavala"
date: "2010-08-03"
categories: ["telugu", "archive", "పద్యాలు", "వీడియోలు"]
---

విరామాన్ని జాగ్రత్తగా గమనించండి. "మొదటి, పెళ్ళివీడియో". "మొదటి పెళ్ళి" - వీడియో కాదు :). యూట్యూబ్ ఇంకా ప్రపంచానికి "పూర్తిగా" తెలియనప్పుడె మా వీడియో వికారం మొదలైంది. అది కూడా, ఇండియా అసోసియేషన్ అధ్యక్షపదవికి జరిగే వార్షిక ఎన్నికలతో. అప్పటినుంచి కొనసాగుతూ, మొత్తం ఒక 22 వీడియోలు రూపొందించడంలో ఏదో ఒక పాత్రపోషించాను. వీటన్నిటికీ విభిన్నమైనదే పెళ్ళివీడియో కి వీడియోగ్రాఫర్ గా పనిచెయ్యడం.  
"మా పెళ్ళి ఫలానా తారిఖున జరగబోతోంది. వీడియోగ్రాఫర్ ని కుదుర్చుకోవడానికి సమయం సరిపోలెదు. అందుకని మీ క్లబ్ లో ఎవరైనా అందుబాటులో ఉంటే నన్ను సంప్రదించండి"  
అని పెళ్ళికూతురినుంచి ఒక ఈమైలు స్టూడెంటు ఫిల్మ్ క్లబ్ మైలింగ్ లిస్ట్ కి వచ్చింది. అప్పటివరకు చేసిన వాటితో విసుగు రావడం వలన, ఈ పెళ్ళికి వీడియోగ్రాఫర్ గా పనిచేస్తే పుణ్యం-పరమార్ధం అనుకుంటూ..  
"నే చేస్తాను. కానీ, నా దగ్గర ఉన్నది - ఒక డొక్కు కెమారా. అతిసాధారణంగా ఉంటుంది. ఎడిటింగ్ చెయ్యడానికి సమయంలేదు. వీడియో ఒక జ్ఞాపికంగా మాత్రమే ఉపయోగపడుతుంది గానీ, అంతకుమించి సీను ఉండదు. మీరు వీటికి ఒప్పుకుంటే, మీతో మరిన్ని వివరాలు మాట్లాడతాను"  
అని టపా పెట్టను. వాళ్ళకి ఇంకెవరూ దొరకకపోవడంతో, నన్ను వాళ్ళ వీడియోగ్రాఫర్ గా అంగీకరించడం తప్పించి, వేరే గత్యంతరం లేకపోయినట్టుంది .  
పెళ్ళికూతురిని కలిసి, ఎక్కడ, ఏమిటి లాంటి విషయాలని కనుక్కొన్నాను. బహుసా అది సెమెస్టర్ ముగుస్తున్న సమయం కావచ్చు, ఆవిడకి మాట్లాడ్డానికి కూడా తీరికలేకపోయింది. ఏమైనా ప్రత్యేకమైన సూచనలిస్తుందేమనని, ఆశించి భంగపడ్డాను. ఇంక సరే అని - నా రిసెర్చ్ మొదలుపెట్టా. పెళ్ళి వీడియో తీసేటప్పుడు ఏఏ జాగ్రత్తలు తీసుకోవాలి. ముఖ్యంగా, అమెరికన్ల వివాహంలో ముఖ్యఘట్టాలేంటి, లాంటివన్నె రాసి ఒక లిస్ట్ పెట్టుకున్నాను. నాకున్న బడ్జెట్లోనే - ఒక ట్రైపాడ్, ఒక బుల్లి లైటు, పవర్ ఎక్స్టెంషన్ కార్డు, బేటరీపేక్ - ఇవన్నీ జోలెలో వేసుకొని, వివాహ వేదిక కి చేరుకున్నాను. ఇది, యూనివర్సిటీలోనే ఉండే, ఆల్ ఫైత్ చాపెల్ - బెస్ట్ మేన్, బెస్ట్ వుమెన్, చిన్నపిల్లలు తెల్లగౌన్లలో గులాబీ పువ్వులు పట్టుకుని అటూ ఇటూ తిరుగుతూ - కొంచం సందడిగానే ఉంది.  
నేను పెట్టుకున్న కార్డినల్ రూల్ - మన తెలుగు పెళ్ళిళ్ళలో లాగ, వీడియోగ్రాఫర్ కథానాయకుడు కాకూడదు. ఏది చేసినా తెరవెనుకే ఉండాలి- అని. అందుకు తగ్గట్టే, సెంటర్ స్టేజికి ఆటొక చివర ఇటొక చివర వాళ్ళదగ్గరున్న గుప్తులకాలంనాటి రెండు కెమారాలని అమర్చి, నేను మధ్యలో భుజంమీద కెమేరా పెట్టుకొని లో ప్రొఫైల్ లో కూర్చొన్నాను. నేను రాసుకొన్న లిస్ట్ లో జరుగుతున్న అంశాలు ఒకటి ఒకటి అవుతున్నాయి, అంతా సవ్యంగా జరిపోతోదని అనుకుంటుండగా, అప్పుడు తగిలింది మొదటి షాక్. వాళ్ళా ఇంటి పెద్దావిడొకామె, చేతిలో బ్రెడ్ పట్టుకొని, మంత్రంజల్లిన నీళ్ళో, వైనో జల్లుతూ, ఏవో వల్లిస్తొంది. ఆ బ్రెడ్ చూడగానే అర్ధమయ్యింది, ఇది క్రిస్టియన్ల పెళ్ళి కాదు, యూదులపెళ్ళని ( హిస్టరీ చానల్ లో బ్రెడ్ గురించి, చెప్తూ, ఇలా జడలా అల్లే బ్రెడ్ జూయిష్ సాంప్రదాయమని, చెప్పండం గుర్తుకొచ్చింది). మరి వీళ్ళ ఆచారంలో ముఖ్య ఘట్టాలేంటో, ఎక్కడ ఏ షాట్స్ తీయ్యాలో అన్న ప్లేనింగ్ తప్పింది. ఇంక చేసేదేమీలేక, సందర్భానుసారం, స్టిల్ ఫొటోగ్రాఫర్ ని గమనిస్తూ, లాగించేసాను. ఇదంతా దాదాపు ఒక గంటన్నర పట్టింది. చివర్లో ఇద్దరితరపు కుటుంబ సభ్యుల గ్రూప్ ఫొటోతో పెళ్ళి అయిపించేసారు.  
ఇంక మిగిలింది డిన్నర్. ఇది మెమోరియల్ స్టూడెంట్ సెంటర్ లో. టేబుళ్ళనీ చాలా నీట్ గా సర్ది ఉన్నాయి. ఎక్కడ చూసినా నలుపే. ఆఖరికి, మూతి-ముడ్డీ తుడుచుకొనే పేపర్ నేప్కిన్స్ కూడా. ఎవడిగోల వాడిది టైపులో అందరి దృష్టి భోజనం మీదే . ఈ నవ దంపతులు మాత్రం ప్రతీ టేబుల్ దగ్గరకి వెళ్ళి అందరినీ పలకరిస్తున్నారు. అతిధులు తెచ్చిన గిఫ్టులని స్వీకరించడనికి ప్రత్యేకంగా ఒక టేబుల్ దగ్గర వారి స్నేహుతులు కాపలా ఉన్నారు. ఇంగ్లిష్ సినిమాల్లో చూపించినట్టు, పెళ్ళికూతురు పూలసజ్జ విసిరితే, ఎవెరో ఒక అమ్మాయి పట్టుకొని తెగ మురిసిపోయింది. తరువాత ఒక వింత ఆచారాన్ని గమనించాను. పెళ్ళి కూతురు కుర్చీలో కూర్చొని ఉంటే, పెళ్ళి కొడుకు వెళ్ళి, ఆమె గౌనులో కిందనుంచి చెయ్యిపెట్టి కితకితలో ఎవో పెట్టాలి. ఎంత లోపలికి చాపితే అంత సరదా కాబోలు. అదేం సరదావో - అంత మంది సమక్షంలోనిన్నూ. తరువాత, ఇద్దరూ కలిసి, డీ.జే పాటకి అనుగుణంగా డాన్స్ చేసారు - అందరూ చప్పట్లు కొడుతూండగా. ఇలా దాదాపు చివరికొచ్చేసాం. అలా అంతమంది అతిధుల్ల్నీ కవర్ చేసుకుంటూ, అధ్భుతంగా డెకరేట్ చేసిన కేక్, పళ్ళు, ఇలాంటివన్నీ వెనక్కి నడుస్తూ తీస్తూ, తీస్తూండగా  
కం||  
తుళ్ళిపడె నూతన వధువు  
భళ్ళున పగల స్మృతిశిఖరపటరాజమ్ముల్  
ఘొల్లనె పతి విభ్రాంతిన్.  
ఛెళ్ళుమనగ చెంప, ఇల్లు జేరితి తుదకున్.  
ఒక్కసారి పెళ్ళికూతురు అదిరి (తుళ్ళి) పడింది. పెళ్ళి కొడుక్కి ఏమైందో కాసేపు అర్ధంకాలేదు. ఒక ఫొటొస్టేండ్ కి నా కాలు తగలండంతో, వాళ్ళిద్దరూ కలుసున్న ఫొటొ (స్మృతిశిఖరపటరాజం) ఒకటి కింద పడి, అద్దం భళ్ళుమని పెద్ద శబ్ధం చేస్తూ విరిగిపోయింది. నా మనసులో వంద తెలుగు సినిమాలు గిర్రుమని వంద రోజులాడినట్టినిపించింది. మీకు తెలుసుగా - ఒక ఫొటొ గోడమీదనుంచి కింద పడి అద్దం పగిలింది - అంటే అర్ధం. అంతా ఒక క్షణం పాటు నిశ్శబ్ధం. అందరి చూపు నా వైపే. పెళ్ళికూతురు నోరెళ్ళబెట్టింది. పెళ్ళి కొడుకు చెంప ఛెళ్ళుమనేట్టు ఒక చూపు చూసి, మళ్ళీ సర్దుకొని, తనే ఆ అద్దం ముక్కలని ఏరడానికి ముందుకొచ్చాడు. ఇద్దరికి క్షమాపణలు చెప్పి, అతని స్నేహితులు కొందరు, నేను కలిసి గాజుపెంకులన్నె ఎత్తి చెత్తబుట్టలో వేసి, నేను కనుమరుగయ్యాను. ఇంక మరి మధ్యలోకి వెళ్ళకుండా జూమ్ తో కానిచ్చేసా. ఇంకో పావు గంటికే మొత్తం కార్యక్రమం అయిపోవడం, గుడ్డిలో మెల్ల. కథానాయకుడు సరే సరి, ఇలా విలన్నో, కమెడియన్నో అయిన ఇంత దారుణమైన అనుభవం జీవతంలో ఇంకెప్పుడూ ఎదురు కాకూడదురా నాయనా, అనుకుంటూ, తలదించుకొని, కాళ్ళీడ్చుకొంటూ, ఇంటికిచేరాను.  
మర్నాడు వెళ్ళి వాళ్ళ పెళ్ళి డీ.వీ.డీ. ని పెళ్ళికూతురికి అప్పజెప్తే, చేతిలో ఒక ఇరవై డాలర్లు పెట్టింది. పెట్టిన ఖర్చు కూడా తిరిగిరాలేదు. బహుసా, ఆ ఫొటొ వెల మినహాయించినట్టుంది. ఇలా, నేను పనిచేసిన మొదటి పెళ్ళి వీడియో - అదే, మొదటీ "పెళ్ళి వీడియో" మరచిపోలేని జ్ఞాపకాల్ని మిగిల్చింది. వాళ్ళ సంగతేమో మరి :).
