---
title: "Space-Frequency Coded OFDM"
subtitle: "Alamouti coding across OFDM sub-carriers for frequency-selective fading channels"
author: "Soma S. Dhavala"
---

# Space-Frequency Coded OFDM

These notes describe a space-frequency coded OFDM system consisting of two transmitters and a single receiver. A simple Alamouti space-time code is used, and an M-ary PSK modulation maps the symbols across an OFDM channel. We also consider a variation of the scheme that spreads additional symbols across the time-frequency plane, aiming to increase the transmission rate without changing the modulation employed or increasing the bandwidth. A Rayleigh frequency-selective slow-fading channel is assumed throughout.

**Key words:** Space time/ frequency coding, OFDM, MIMO, frequency-selective channel

## Introduction

High data rate reliable transmission over wireless channels is seemingly possible due to the advent of Space-time codes. Space-time codes rely on transmit diversity and are particularly suitable when the signal undergoes frequency flat fading due to the channel. In the original space-time code scheme [1], Alamouti showed that it is possible to obtain the same diversity as with multiple receivers. Since then, transmit diversity has been pursued with great interest among the research community. However, the fundamental assumption based on which the scheme works is that the channel is frequency flat, i.e., the coherence bandwidth of the channel is much smaller than bandwidth of the signal which may not be true in wideband communication [2-5]. This assumption may not be generally true in wideband communication systems. For example, high-data rates are made possible with increased resources in terms of bandwidth in WWAN and outdoor wireless networks. There is a need to develop new technologies for providing wideband wireless communications.

OFDM (orthogonal frequency division multiplexing) has matured into a very practicable technique and has been incorporated into the IEEE 802.11a [2]. OFDM splits the channel into sub-channels equal to the no. of carriers under use. Each sub-channel is treated independently and the multiplexed modulated symbols are sent over each carrier. This operation is performed via IFFT at the transmitter side and with FFT at the receiver side. This is another interesting aspect of OFDM.

Thus marrying OFDM with Space-time codes appears very natural in frequency selective fading scenarios. OFDM splits the channel into near frequency-flat sub-channels and Space-time codes exploit the transmit diversity under these frequency-flat sub-channels. Together they form a promising technological alternative for high data rate broadband communications.

These notes consider a 2 x 1 Alamouti space-time code with OFDM (which is called a space-frequency code, as the space-time code is transmitted over another carrier rather than another time-slot). A frequency selective Rayleigh channel is assumed. Information bits are M-ary PSK modulated, which are then converted into space-frequency codes. These are multiplexed to form OFDM frames for final transmission. A variation that improves the system is also considered: information about a few more symbols is spread over all the carriers by varying both the phase and energy of that constellation in a controlled manner. The encoding and decoding mechanisms are described below.

## System Description

- No. of carriers: $N_c$
- Total Bandwidth: W Hz
- Input symbols (M-ary coded) in a frame: $X_0, X_1, \ldots, X_{N_c}$
- Modulation: M-ary PSK
- No. of Tx: 2
- No. of Rx: 1
- Space time code: Alamouti 2 x 2 code

Channel Model [3][4][5]:

No. of taps: L = 6

$$
h_i(n) = \sum_{l=1}^{L} a_l(n)\,\delta(t - l/W)
$$

where $a_l$ are zero mean complex Gaussian random variables with variance 1/L

$$
H_i(k) = \sum_{j=1}^{N_c} h_i(j)\,\exp(-j2\pi kn / N_c)
$$

Space-frequency code at Tx -1 (total $N_c$ symbols) :

$$
\mathbf{X}_1 = [\,X_{0,}\ -X_1^*, \ldots, X_{N_c-2}\ -X_{N_c-1}^*\,]^T
$$

Space-frequency code at Tx -2 (total $N_c$ symbols):

$$
\mathbf{X}_2 = [\,X_1,\ X_0^*, \ldots, X_{N_c-1}\ X_{N_c-2}^*\,]^T
$$

Received symbols at the receiver:

$$
\mathbf{Y}_e = \mathbf{\Lambda}_{1e}\mathbf{X}_{1e} + \mathbf{\Lambda}_{1e}\mathbf{X}_{2e} + \mathbf{N}_e
$$

$$
\mathbf{Y}_o = \mathbf{\Lambda}_{1o}\mathbf{X}_{1o} + \mathbf{\Lambda}_{2o}\mathbf{X}_{2o} + \mathbf{N}_o
$$

where

$$
\mathbf{X}_{ie} = \mathbf{X}_i(2k)
$$

$$
\mathbf{X}_{io} = \mathbf{X}_i(2k+1),\ k = 0,1 \ldots Nc/2
$$

and $\mathbf{N}_e, \mathbf{Y}_e, \mathbf{\Lambda}$ defined likewise.

$\mathbf{\Lambda}$ is a diagonal matrix with $H_i(k)$ as its diagonal elements

The estimated (decoded) symbols (assuming that two adjacent sub-channels have approximately same frequency response) after stripping the cyclic prefix and performing FFT operation on the received symbols, are [6],

$$
\hat{\mathbf{X}}_e = (|\mathbf{\Lambda}_{1e}|^2 + |\mathbf{\Lambda}_{2e}|^2)\mathbf{X}_e + \mathbf{\Lambda}_{1e}^*\mathbf{N}_e + \mathbf{\Lambda}_{1e}\mathbf{N}_o^*
$$

$$
\hat{\mathbf{X}}_e = (|\mathbf{\Lambda}_o|^2 + |\mathbf{\Lambda}_{2o}|^2)\mathbf{X}_o + \mathbf{\Lambda}_{2e}^*\mathbf{N}_e - \mathbf{\Lambda}_{1o}\mathbf{N}_o^*
$$

This equation enables us to study the performance of the scheme completely in the constellation domain.

## Over-loaded OFDM

A natural idea is to spread a message symbol onto all the carriers. An explanation is sought to suggest a way of spreading the message symbols. In the OFDM case, message symbols are modulated on to separate carriers which are orthogonal. Suppose if we use time-varying signals to modulate these message symbols, we can overload the time-frequency plane i.e., besides all the carriers, we can modulate some additional symbols using these time-varying signals. In the context of M-ary FSK, this affects the constellation in two ways:

The phase as well as radius of the constellation is varied. In the regular M-ary OFDM, the constellation is cylinder. The radius is equal to the symbol energy and each section of the cylinder corresponds to a carrier. When chirp signals are used to modulate additional symbols, then, the phase of the message symbol in a particular is corrupted by the phase of the chirp signal and phase of the message symbols this chirp signal is carrying. The radius is affected by the addition of instantaneous energy of the chirp signal. The modified constellation can be represented as:

$$
\begin{bmatrix} S'_o \\ \vdots \\ S'_{Nc} \end{bmatrix}
=
\begin{bmatrix}
1 & 0 \ldots 0 & W_1^0 \ldots W_{Ne} \\
\vdots & & \\
0 & \ldots\ 1 & W_1^{Nc} \ldots W_{ne}^{Nc}
\end{bmatrix}
\begin{bmatrix} \vdots \\ S_{Nc} \\ S_{Nc+1} \\ \vdots \\ S_{Nc+Ne} \end{bmatrix}
$$

$S_i$ : mapped symbol $i \in [0, Nc - 1]$

$W_i^k$ : weight of ith symbol over ith carrier

$$
\sum_{i=0}^{Nc-1} W_i^k = 1
$$

These modified symbols are now used to form the space-frequency codes. The decoding is performed by inverting the weight matrix to obtain approximate Nc+Ne constellation vectors which are then subjected to M-ary PSK detection. The choice of the weight matrix affects the performance severely. It is of much interest to study how to design the weight matrix for a given modulation and given number of carriers. Constructing such a pseudo-orthogonal weight matrix is a problem of great interest.

## Conclusions

For a large number of carriers at a given bandwidth, the symbol error rate is expected to be almost the same, because the sub-channels are frequency flat, each sub-channel can be used to its full capacity, and the assumption that adjacent sub-channels are identical also holds. As M increases, the SER curve shifts: to achieve the same SER, more power is required to push the constellation further away from the origin and offer more resolution or detection capability. For the over-loaded scheme, one would expect little degradation in the SER, because the Ne extra symbols are spread over all the carriers and all the carriers suffer independent fading, so frequency diversity should offer some advantage. This motivates the design of new pseudo-orthogonal weight matrices.

## References

[1] S.M. Alamouti, "A simple transmitter diversity scheme for wireless communications," *IEEE JSAC*, Vol. 16, No. 3, pp 1451-1458, 1998

[2] http://www.nari.ee.ethz.ch/commth/pubs/files/proc03.pdf

[3] http://www.tele.ntnu.no/projects/beats/Documents/GesbertMIMOlecture.pdf

[4] D. Agarwal, V. Tarokh, A. Naguib, and Nambi Seshadri, "Space-time coded OFDM for High Data Rate Wireless Communication over wideband," *Proc. VTC*, Ottawa, Canada, Vol. 3, pp. 2232-2236, 1998

[5] M, *Torabi, M.R. Soleymani*, "Adaptive bit allocation for space-time block coded OFDM system," *Acoustics, Speech, and Signal Processing, 2003. Proceedings. (ICASSP '03). 2003 IEEE International Conference on*, Volume: 4 , 6-10 April 2003, Pages: IV - 409-12 vol.4

[6] *Lee, K.F.; Williams, D.B.*, "A space-frequency transmitter diversity technique for OFDM systems," *Global Telecommunications Conference, 2000. GLOBECOM '00. IEEE*, Volume: 3 , 27 Nov.-1 Dec. 2000, Pages: 1473 - 1477 vol.3
