---
title: "రెండవ ప్రపంచ తెలుగు సాహితీ సదస్సు - ఫిబ్రవరి 14-16, హైదరాబాదు"
description: "వంగూరి ఫౌండేషన్ ఆఫ్ అమెరికా వారు రెండవ ప్రపంచ తెలుగు సాహితీ సదస్సుని మధ్య శ్రీత్యాగరాయగానసభ, చిక్కడపల్లి, హైదరాబాదులో నిర్వహిస్తున్నారు. కొన్ని ముఖ్యవివరాలు:"
author: "Soma S Dhavala"
date: "2009-02-09"
categories: ["telugu", "archive"]
---

వంగూరి ఫౌండేషన్ ఆఫ్ అమెరికా వారు రెండవ ప్రపంచ తెలుగు సాహితీ సదస్సుని  
Feb 14-16,2009  
మధ్య శ్రీత్యాగరాయగానసభ, చిక్కడపల్లి, హైదరాబాదులో నిర్వహిస్తున్నారు. కొన్ని ముఖ్యవివరాలు:  
మొదటిరోజు (నిర్వహణ: డా|| వంగూరి చిట్టెన్ రాజు) ఉ: 9.30 నుంచి  
- ఇంద్రగంటి శ్రీకాంతశర్మ స్వాగతోపన్యాసం  
- సి.నా.రె ప్రారంభోపన్యాసం  
- తెలుగు ఉపాధ్యాయులకు సన్మానములు (గ్రహీతలు: డా|| తెన్నెటి సుధాదేవి, ఆలూరు శిరోమణి, ఇంద్రగ్ంటి అన్నపూర్ణ)  
- డా|| ఆవుల మంజులత, గొల్లపూడి మారుతీరావు ల ప్రసంగాలు  
- పుస్తకావిష్కరణలు  
- తెలుగు వివిధ దశలు-ఉద్యమాలు పై పోరంకి దక్షిణామ్మూర్తి, విహారి, వల్లావజ్జుల పతంజలి శాస్త్రి, జె. బాపురెడ్డి, ఆచార్య ముదిగొండ శివప్రసాద్ ల ప్రసంగాలు  
- లలిత సంగీతం ( ప్రత్యేక ఆహ్వానితులు వింజమూరి అనసూయాదేవి) సా: 7.00 గంటలకు  
రెండవరోజు: (నిర్వహణ: ఇంద్రగంటి జానకీబాల) ఉ: 9.30 నుంచి  
- ముఖ్యాతిధులు ( అబ్బూరి చాయాదేవి, మల్లది సుబ్బమ్మ, వాసా ప్రభావతి, సి. ఆనందారామం  
- వంద సంవత్సరాల తెలుగు సాహిత్య ప్రస్థానంలో రచయిత్రులు, స్త్రీల సాహిత్యంలో వాదనలు, రచనల్లో కుటుంబం-సంఘం-స్త్రీల సమస్యలు  
- సా 6.00 లకు రామాయణంలో స్త్రీపాత్రలలో అంతరంగ నివేదనం (కౌసల్య, శబరి, కైక, సీత మొదలగు పాత్రల సంభాషణ, నాటికలాంటిది)  
మూడవరోజు: సా: 6.00 నుంచి  
- మాధ్యమాలలో తెలుగు సాహిత్యం: సినీ రచయితల వేదిక (బలభద్రపాత్రుని రమణి, గొల్లపూడి, పరుచూరి గోపాలకృష్ణ, చంద్రబోసు, అందెశ్రీ, s.v.రామారావు, వడ్డేపల్లి కృష్ణ  
- ముగింపు: శ్రీ గొల్లపూడి మారుతీరావు గారికి జీవిత సాఫల్య పురస్కారం  
పూర్తి వివరాల కొరకు:  
వంగూరి ఫౌండేషన్ ఆఫ్ అమెరికా  
Vamsee International Campus  
Satyasaipuram, Kuntloor(V),  
Hayatnagar(M)  
R.R. (Dist.)  
Hyderabad, 501 505, AP  
Cell: 98490 23852  
email: ramarajuvamsee AT yahoo.co.in  
brochure చూడండి  
తెలుగుసాహిత్యాభిమానులు, ఔత్సాహిక రచయితలు, ఈ అవకాశాన్ని సద్వినియోగం చేసుకుంటారని ఆశిస్తూ...
