---
title: "నెలనెలా వెన్నెల్లో జె.వి.రమణమూర్తి గారి మెరుపు"
description: "ఈ నెల \"హ్యూస్టన్ లో నెలనెలా వెన్నెల\"లో జె.వి. రమణమూర్తి గారు ప్రత్యేక వక్తగా పాల్గొన్నారు. వింజమూరి అనసూయ గారు కూడా పాల్గొన్నారు."
author: "Soma S Dhavala"
date: "2010-08-22"
categories: ["telugu", "archive", "పద్యాలు", "సినీమా"]
---

ఈ నెల "హ్యూస్టన్ లో నెలనెలా వెన్నెల"లో జె.వి. రమణమూర్తి గారు ప్రత్యేక వక్తగా పాల్గొన్నారు. వింజమూరి అనసూయ గారు కూడా పాల్గొన్నారు.  
రమణమూర్తిగారి -కంచు కంఠం, స్ఫురద్రూపం, స్పష్టమైన ఉఛ్ఛారణ, అన్నిటికీ మించి, నాటకం పట్ల ప్రేమ - ఆయన్ని రంగస్థలం పై అత్య్త్తమనటుడిగా తీర్చిదిద్దాయనడంలో సందేహంలేదు. అసలు నటన అంటే నిర్వచనం ఆయన మాటల్లో - acting is the art of listening. అలాగే దర్శకుడు అంటే - expert audience. సినిమాకి, నాటకానికి ఉన్నతేడా, సినిమాలో దర్శకుడి పాత్రఏంటి -ఇంకా ఎన్నో విషయాలు ప్రేక్షకులతో పంచుకున్నారు.  
మరి కన్యాశుల్కం గురించి ప్రత్యేకంగా చెప్పఖ్ఖరేదు - అది ఆయన ఊపిరి. దూరదర్శన్ వారి కోసం కన్యాశుల్కం - మొత్తం 19 భాగాలు -నిర్మించారు. . ఈ version లో ఆయన గిరీశాన్ని చివర్లో పరివర్తన చెందిన వాడిగా మలిచేరు. ఇదే విషయాన్ని ఒక ప్రేక్షకుడు (సుదేష్) అడుగుతూ - "అప్పారావు గారికి మాత్రమే పాత్రని, కథని మార్చే హక్కు ఉంది. మీ వివరణ ఏంటి" అన్నందుకు, దాదాపు అరగంటపైన ఆ ఒక్క విషయంమీదే మాట్లాడుతూ -  
అప్పారావు గారు అప్పటి సాంఘిక పరిస్థుతలకి కొంచం తలవంచుతూనే - damn it కథ అడ్డం తిరిగింది - అంటూ పాత్రని సంశయంలో పడవెయ్యాల్సి వచ్చింది  
అంటూ అసలు కన్యాశుల్కం రాయడానికి ప్రేరేపించిన వాతావరణం గూర్చికూడా వివరించారు. నాటకంలోని పాత్రలని ఉటంకిస్తున్నప్పుడు నాటకం చూసిన అనుభూతి కలిగింది.  
వారికినా పద్యకుసుమాంజలి:  
ఉ||  
జొన్నలగడ్డయన్ననది ఉజ్వలతారలబింబరూపమౌ  
వెన్నెలగడ్డయే. కలడె వేరె గిరీశము కావ్యకన్యకా  
వన్నియతెచ్చినట్టునిల? వ్యంగ్యము, రౌద్రము, మోహనమ్మువం  
టన్నిరసమ్ములన్ గనెడి ఢాకిని ఢంకము దద్దరిల్లదా?  
ఒక్క నాటకం గిరించే కాకుండా సినిమా విశేషాలు కూడా పంచుకున్నారు. ఆయన మొదటిసారి NTR ని కలవడం కోసం, సెట్ లోకి వెళ్తే, ఎదో షూటింగ్ మధ్యలో ఉన్న NTR షూటింగ్ ఆపి - "బ్రదర్, మీరు నన్ను క్షమించాలి. మీ పాత్ర (గిరీశం) ని నేను వెయ్యాల్సి వచ్చింది...."అంటూ కరచాలనం చేసి పరిచయం చేసుకున్నారుట. ఇలా ఎన్నో. కార్యక్రమం అయిపోయిన తరువాత ఒక ప్రేక్షకుడి (రవి) స్పందన ఇలా ఉంది:  
I came to the program with total focus on food. I was very hungry when I arrived wanting to eat immediately but I completely forgot about it as the program started unfolding. The evening turned out to be another real vennela. I really liked the answers from him. His answers are almost like a presentation of a thesis. He can be easily awarded a doctorate on Kanya Sulkam. His subject matter expertize impressed me. I never read any books all my life. Many friends asked me either read or watch Kanya Sulkam but I did not unfortunately (fortunately now?).  
I feel that I am very blessed in many ways and listening about the Kanya Sulkam from the original Gireesam (patent owner?) is one of those fortunes. His narration or analysis of the writer's perspective with all possible permutation that are required in all the characters is a well thought out and structured observations. I found him very scientifically entertaining.  
I am very fortunate to come across great teachers all my life as all my teachers since my childhood always understood me and did their best to expand or clarify on my questions. I found one such teacher in him. His observation are very genuine and authentic in nature. He did not even miss to share his thoughts on SWAASA n DHYAASA which really impressed me. His remarks on DHYAAASA (mind and its tricky nature) seemed like passing remarks and silly or lighter side of the discussion but it sounded like the essence of his life. In fact he shared a great secret with us in a very casual manner.  
His very well structured ( like SQL) presentation on the issues of those times and the evolution of Kanya Sulkam seemed like a dissertation. His talk not only covered his career but also his spiritual perceptions too. I somehow felt he is very simple and honest to the best of his ability. I found one more great teacher in him. I am a product of many great teachers and good bosses. n short it is a great learning experience for me personally. I will watch Kanya Sulakam.  
The best part of this great man is he came without expecting anything from the crowd. He did not come to sell, market his products or any prospective ambitions and did not have any worries that somebody would steal his ideas. This aspect highlights his contentment which is career and personal life.  
I met a great person.  
వింజమూరి అనసూయగారు కూడా దేవులపల్లి కృష్ణశాస్త్రి గారి గురించి కొన్ని విషయాలు ప్రస్తావించారు. ఇదే సంధర్భంలో - సాహితీ-ప్రియుడు బ్లాగర్ సేకరించిన అరుదైన కృష్ణశాస్త్రి గారి ప్రసంగం గురించి వంగూరి చెట్టెన్ రాజు గారు ప్రస్తావించారు. ఆ సభలో అనసూయగారు ప్రారంభగీతం పాడేరుట. "జయ జయ ప్రియభారత.." పాట గురించి చెబుతూ, ఈ పాటకి తనే స్వరకల్పన (ఇళయరాజా కాదు) చేసాననీ కూడా చెప్పారు. 91 ఏళ్ళవయస్సులో ఆవిడా తన మూడవ పుస్తకం - ఎందరో మహానుభావులు - రాసేపనిలో ఉన్నట్టు చెప్పారు.  
వారికినా పద్యకుసుమాంజలి:  
ఆ.వె||  
కృష్ణశాస్త్రి కైత కృతులబాసలు నేర్పు,  
వింజమూరి గురుతుదొంతర వింజామర విసరా  
స్వరఝరీలలామ సౌరభం గ్రోలగ  
మనసున మల్లెల మాలలూగెన్ నా మదిన్ అహా!  
ఈ వెన్నెల వీడియో లభించినప్పుడు లింక్ పోస్ట్ చేస్తాను.
