---
title: "విజయనగరం కౌముదీపరిషత్ - పంచసప్తతి కల్యాణకౌముది వసంతోత్సవాలు"
description: "విజయనగరం కౌముదీపరిషత్ పంచసప్తతి కల్యాణకౌముది వసంతోత్సవాలు - 10th Oct to 12th Oct, 2010. ఆనందగజపతి ఆడిటిరియంలో. కార్యక్రమ వివరాలు సంక్షిప్తంగా:"
author: "Soma S Dhavala"
date: "2010-10-08"
categories: ["telugu", "archive"]
---

విజయనగరం కౌముదీపరిషత్ పంచసప్తతి కల్యాణకౌముది వసంతోత్సవాలు - 10th Oct to 12th Oct, 2010. ఆనందగజపతి ఆడిటిరియంలో. కార్యక్రమ వివరాలు సంక్షిప్తంగా:  
10-10-2010  
1) ఉ. 9 గం|| నుండి  
ఉదయరాగం  
- సాహితీవేత్తలకి సత్కారాలు  
- కొత్త చివుళ్ళు (యువకవులచే 12 భిన్న సాహిత్యప్రక్రియలు)  
- కనాశుల్కం చెణుకులు (A. B. సుబ్బారావు)  
- దేవీభాగవతం (డా|| కె. మలయవాసిని)  
2) సా. ౫ గం|| నుండి  
- అందెల సందడి (భరతనాట్య ప్రదర్శన)  
- శ్రీమద్రామాయణ కల్పవృక్షం, శ్రీ విశ్వనాధకవితావైభవం (మల్లంపల్లి అమరేశ్వరప్రాద్)  
-కవిబ్రహ్మ తిక్కనకవితావైదుష్యం (ఆచార్య కొంపెల్ల రామసూర్యనారాయణ)  
-పట్టుతేనె పలుకులతీపి (డా|| శ్రీనివాస రామానుజం)  
-పద్యనైవేద్యం (ఘంటశాల ఆరాధకులు - ధవళ విశ్వకుమార్)  
11-10-2010  
1) ఉ. 9 గం|| నుండి  
-రసతరంగిణి (డా|| శ్రీమతి వి. వెంకటరాణి, AIR విశాఖపట్టణం)  
-మహదేవ వర్మ (హిందీ) సాహితీ వైభవం (డా|| చాగంటి తులసి)  
-కృష్ణశాస్త్రి కవితామాధుర్యం (కె. తిరువేంగళమ్మ)  
-కల్పవృక్షం కాంతులు (డా|| M.V. రమణారెడ్డి)  
-తీపి చూపులు (బాలలచే నేత్రావధానం)  
2) మ. ౩ గం|| నుండి  
-సంగీతజ్ఞులకు తాంబూల సమర్పణం  
-సాలూరికి స్వరనీరాజనం (విజయతరంగిణి - భీష్మ ఆర్కెష్ట్రా)  
౩) సా. 6 గం|| నుండి  
-ఆనంద బృందావనం (DD సప్తగిరి డైరెక్టర్ డా|| పి. మధుసూధనరావు)  
-భారతీయసాంప్రదాయ సౌందర్యం (రామకృష్ణానంద వారి ప్రసంగం)  
12-10-2010  
1) ఉ. 9 గం|| నుండి  
వెన్నల తళుకులు (ప్రసంగాలు)  
- కాళిదాసు కళావిలాసం (శ్రీమాన్ గుదిమెళ్ళ రంగాచార్యులు)  
-వరూధినీ వయ్యారం (RMS శాస్త్రి)  
-భాసుని హాసతరగం (వేడూరు సత్యన్నారాయణమూర్తి)  
-పోతన భాగవతం (పి. ఢిల్లీస్)  
2) సా. 5 గం|| నుండి  
వసంత విలాసం  
-శ్రీమద్రామాయణంలో శాస్త్రవిజ్ఞానం (కె. పాండురంగ విఠల్)  
-భువన విజయం (కె. కోటారావు బృందం)  
గౌరవాధ్యక్షులు - మానాప్రగడ శేషసాయి  
సభాధ్యక్షులు - ధవళ సర్వేశ్వరరావు  
కార్యదర్శి - అడిదం శారద  
కార్యనిర్వహణాధ్యక్షులు - పి.వి. నరసింహరాజు  
విశిష్ఠ అతిధులు - బొత్స ఝాన్సీ (M.P), పూసపాటి ఆశోక్ గజపతి (M.L.A), బొత్స సత్యనారాయణ (M.L.A), కోలగట్ల వీరభద్రస్వామి (Ex. M.L.A)  
కౌముదీ పరిషత్ - స్థాపన 1935  
వ్యవస్థాపక అధ్యక్షులు - పట్రాయని సీతారామ శాస్త్రిగారు  
కౌముదీపరిషత్ గత కార్యవర్గ ప్రముఖులు - పంతుల లక్ష్మీనారాయణ శాస్త్రులు (సంస్కృత కాలేజి) , వసంతరావు వెంకటరావు (M.R. కాలేజి), డి.ఎల్. నారాయణ (M.R. కాలేజి), పేరీ సూర్యనారాయణశాస్త్రి (సంస్కృత కాలేజి), తుమరాణ సత్యన్నారాయణ.
