---
title: "పద్యం - వృత్తాలు - అంకెలు"
description: "సాంప్రదాయకంగా మనం పద్యాల ఛందస్సుని నేర్చుకున్నప్పుడు \" ఈ పద్యానికి ఈ గణాలు ఫలానా వరుసక్రమంలో రావాలి\""
author: "Soma S Dhavala"
date: "2009-04-10"
categories: ["telugu", "archive", "పద్యాలు"]
---

సాంప్రదాయకంగా మనం పద్యాల ఛందస్సుని నేర్చుకున్నప్పుడు  
" ఈ పద్యానికి ఈ గణాలు ఫలానా వరుసక్రమంలో రావాలి"  
అని నేర్చుకుంటాం. ఉదాహరణకి, ఉత్పలమాల తీసుకుందాం.  
"భ ర న భ భ ర వ"  
UII - UIU - III - UII - UII - UIU - IU

అనే గణాలు వరుస క్రమంలో ప్రతిపాదంలోనీ రావాలి.  
అనగా లఘువులు, గురువులు (మొత్తం కలిపి 20) ఈ క్రమంలో రావాలి. అదే లఘువుని "౦" గానూ, గురువుని "1" గానీ గుర్తించామనుకోండి: అప్పుడు వచ్చే సంఖ్య  
UII - UIU - III - UII - UII - UIU - IU  
100 - 101 - 000 - 100 - 100 - 101 - 01  
ఆ సంఖ్యని దశాంసమానంలో రాస్తే 607381  
ఒకవేళ ఎక్కడైనా ఒక గణం తప్పయ్యిందనుకోండి, ఉదాహరణకి, చివరి "IU" కి బదులుగా "II" అనే గణాలు మీపద్యంలో పడ్డాయనుకోండి, అప్పుడు, మీ పద్యంలోని పాదం యొక్క సంఖ్య

UII UIU III UII UII UIU II  
100 101 000 100 100 101 00  
607381 - 1 = 607380  
గణం చివరిదయ్యింది కాబట్టి, సులువుగా పట్టేసాం. మరి ఎన్నే చోట్ల తప్పుంటే? ఏ స్థానంలో తప్పుందో కనుక్కోవడం ఎలా?  
అది ఆలోచించే ముందు, exclusive-or లేదా xor అనే బూలియన్ సూత్రం చూద్దాం. దాని ప్రకారం:  
0 + 0 = 0  
0 + 1 = 1  
1 + 0 = 1  
1 + 1 = 0  
దీన్ని ఉపయోగిస్తే మనం తప్పు ఎక్కడుందో ఇట్టే పట్టేయొచ్చు. ఇందాక ఉదాహరణని తీసుకుంటే:  
100 101 000 100 100 101 01  
+  
100 101 000 100 100 101 00  
=  
000 000 000 000 000 000 01  
కాబట్టి, ఎక్కడైతే, మనకి ఒకటి కనిపిస్తుందో, ఆ స్థానాలన్నిటిలోనూ గణం తప్పిందని తెలుస్తుంది. పై ఉదాహరణలో 20 వస్థానంలో తప్పిందని ఇట్టే తెలుస్తుంది కదూ?  
ఇప్పుడు అన్ని (నాకుతెలిసినవి ) వృత్తాలని చూద్దాం:  
ఉత్పలమాల:  
"భ ర న భ భ ర వ  
UII - UIU - III - UII - UII - UIU - IU

100 - 101 - 000 - 100 - 100 - 101 - 01 = 607381  
చంపకమాల:  
న జ భ జ జ జ ర  
III - IUI - UII - IUI - IUI - IUI - UIU  
౦00 - 010 - 100 - 010 - 010 - 010 - 101 = 83093  
మత్తేభం:  
స భ ర న మ య వ  
IUU - UII - UIU - III - UUU - IUU - IU  
IIU - UII - UIU - III - UUU - IUU - IU  
001 - 100 - 101 - 000 - 111 - 011 - 01 = 207085  
శార్ధూలం:  
మ స జ స త త గ  
U U U - I I U - I U I - I I U - U U I - U U I - U  
111 - 001 - 010 - 001 - 110 - 110 - 1 = 469229  
వచ్చే టపాలో జాతులు పైన శోధిద్దాం. అంతవరకు శెలవు.  
(భైరవభట్ల గారు తప్పు సరిదిద్దినందుకు కృతజ్ఞతలు)
