---
title: "my experiences with poetic meter"
description: "In my view, there are two components to writing a poem with meter: technique and art. 1) Technique, the method of construction, can be learned and we need someone to t..."
author: "Soma S Dhavala"
date: "2010-08-19"
categories: ["telugu", "archive", "పద్యాలు"]
---

In my view, there are two components to writing a poem with meter: technique and art.  
1) Technique, the method of construction, can be learned and we need someone to teach us or we need to have sufficient resources for self-help. The online resources like the blogs by few telugu pandits/enthusiasts complement and enhance one's understanding, and sustain the interest, but they are not really a substitute for a formal training session on lines of a one-on-one with instant feedback.  
2) The art component is left to the individual, which gives "personality" to  
the poem. While this can also be taught, just as any other art, it is more  
subjective in nature.  
Why do we need a metered poem?  
My observation is, poems written by many people without any emphasis on the meter, usually have an approximate meter and that approximation is quite close enough to being perfect. This suggest that, if we feel "right/good" about a poem, there might be an underlying meter. Meter is not something that is artificial. It has a "laya". The ganams, yati, prasa, ensure that when chanted/recited, the poem leaves an audible impression on the mind, at least that is the intent, in my opinion.  
Is it hard?  
Recounting my experiences, I used to take about two days to write in a  
simple meter, but it came down to between half-an-hour to half-a-day.  
Readers might be aware that I dont have any saraswati kataksham, but if you  
practice, are persistent and sustain the interest, you can learn it. With  
time, you will master it.  
How do I write (the technique that I am using. By no means this is the only way, but the one that I developed)?  
- Formulate the idea. What do you want to convey? Gather those thoughts,and say it in plain sentences.  
- What are the other ways to express the same idea or similar idea? The vocabulary (eg. synonyms, sandhulu, samasalu, adjectives, fillers, exclamations etc..,) determines the diversity in "expressing" the theme and its strength.  
- Write the approximate version first.  
- Check the meter, make little modifications and go back to step 2 or 1  
if necessary.  
When step-4 requires many modifications, may be it is an indication that something is not looking good. The poem may not be phonetically pleasing and needs rework with the original idea.  
Once you practice enough, the gana vibhajana happens on-the-fly, step-3 and step-4 alternate on-the-fly. By the time you finish, you will have a metered poem.
