---
title: "దేవుపల్లి - దేవునిపల్లే"
description: "కథలు, నవలలు, కవితలు, పుస్తకాలు - చదవడం పెద్దాగా ఇష్టపడని నేను పొరపాటున గొల్లపూడి మారుతీరావు గారి వెన్నెల కాటేసింది నవల(?) కొన్ని పేజీలు తిరగేస్తుంటే, \"దేవుపల్లి\" ప్రస్..."
author: "Soma S Dhavala"
date: "2010-08-05"
categories: ["telugu", "archive", "పద్యాలు"]
---

కథలు, నవలలు, కవితలు, పుస్తకాలు - చదవడం పెద్దాగా ఇష్టపడని నేను పొరపాటున గొల్లపూడి మారుతీరావు గారి వెన్నెల కాటేసింది నవల(?) కొన్ని పేజీలు తిరగేస్తుంటే, "దేవుపల్లి" ప్రస్తావరావడంతో, ఒకసారి గతంగుర్తుకొచ్చింది.  
దేవుపల్లి - విజయనగరం జిల్లా గజపతినగరంకి ఒక ఆరు కి.మీ. దూరంలో, తూర్పుకనుమలకి ఆనుకుని ఒక గ్రామం. ఊరి చివర కొండ దగ్గర, ఒక పాడుబడిన కోట (అంటే ఒక నాలుగు గోడలు) ఉండేది. గజపతి రాజులు అసలు ఇక్కడే కోట కడదామనుకున్నారని, కాని కొండమీదనుంచి శతృవులు సులువుగా దాడి చెయ్యొచ్చని, అందుకే విజయనగరంలో నిర్మించేరని ఇక్కడి వారు చెబుతారు. ఈ ఊరిని "కోట దేవుపల్లి" అనికూడా పిలవడికి ఇదొకకారణం. ప్రధాన జీవనాధారం వ్యవసాయం. పక్కనే కొండ ఉండడం వలన, బొగ్గులు, విస్తరాకులు, కలప- ఇవి కూడా జీవనోపాధి కల్పిస్తుండేవి. అలాగే ఇక్కడ దొరికే నాణ్యమైన మట్టి వలన, ఇటుకలు, కుండలు కూడా తయారయ్యేవి. చేనేత మగ్గాలు కూడా ఉండేవి. ఒక్క ముక్కలో చెప్పాలంటే - గ్రామ స్వరాజ్యానికి ప్రతిరూపంగా ఉండేది మా ఊరు.  
కం||  
నవ్యనురాగాది గుణము  
లవ్యయమౌ సుజలధాతులహరీధాత్రిన్,  
హవ్యవనవాణిగ వినుడు!  
దివ్య కృపన్, దేవుపల్లి దేవుని పల్లే!  
ఇక్కడే నేను రెండవ తరగతి నుంచి పదవతరగతి వరకు చదువుకున్నాను - అమ్మా, నాన్నలిద్దరూ, ఇక్కడి జిల్లా ప్రజాపరిషత్ ఉన్నతపాఠశాలలో అధ్యాపకులవడంవల్ల. హైస్కూలు, ఎలిమెంటరీ స్కూలు, బస్టాండు, లైబ్రరీ, పంచాయితీ ఆఫీసు అన్నీ ఒకేచోటా ఉండేవి. మా ఇంటికీ స్కూలు కీ మధ్యలో ఒక పొలం, అంతే. మా ఇల్లు హరిజన కోలనీ లో ఉండేది. ఆదివారం వచ్చిందంటే చాలు, కోలనీ అంతా మా ఇంటి ముందే సినిమా చూడ్డానికి. చాలామంది పిల్లలు చదువుకోడానికి కూడా వచ్చేవారు - కరెంటు వెలుతురు కోసం.  
హైస్కూలు కి ముందు వెనకా విశాలమైన ఆటా స్థలం ఉండేది. రెండు పక్కల మామిడి తోటలు, అవి దాటితే చెరువు. ఖాళీ దొరికితే, తోటలోకి, లేదా చెరువుకి - స్నేహితులతో, అక్కడ కబుర్లు - ఓహ్.  
చాలా రోజులవరకు ఒక టూరింగ్ టాకీస్ ఉండేది. చాలా మంచి పాత సినిమాలు వేసేవారు. ఇంటికొచ్చే చుట్టాలెవరికైనా, ఇక్కడ సినిమా, చుట్టపొగలమధ్య, చక్కకుర్చీల్లో, చూడ్డం ఎంత సరదావో. నాకు చిరంజీవి పెద్దగహీరో అని తెలియకపోవడనికి, చిరంజీవి బ్లాక్ బస్టర్స్ ఇప్పటికి చాలావరకు చూడకపోవడనికి కారణం, మా ఊర్లో ఎవొస్తే అవే చూడ్డం. స్కూలుకోసం బెనిఫిట్ షో వేసినప్పుడు, ఇదే హాల్లో గేట్ కీపర్ గా పనిచెయ్యడం - ఆహ్.  
కం||  
నవసింగారములొలికెడి  
జవనియె. కల్మషమెఱుగని జనహృది తనెక  
ల్పవనిత. సుఫల చరిత. సుద  
తివరేణ్యిల. దేవుపల్లి దేవునిపల్లే!  
ఇక్కడ ఒక శివాలయం కూడా ఉంది. దీనికి ధ్వజస్థంభాన్ని మా తాతగారు ప్రతిష్టించేరు. హిందీ మేషారే పురోహితుడుగా ఉండేవారు. కాబట్టి పండగ రోజులొస్తే డైరక్టుగా గర్భగుడిలోకి వెళ్ళే సౌలభ్యం ఉండేది. ఒక్క కార్తీకమాసం మాత్రం బాగా జనాలొచ్చేవారు. మామూలు రోజుల్లో రామాలయంలో గాని, శివాలయం లోగానీ, పూజ-పునస్కారాలు పెద్దగా ఉండేవి కాదు.  
ప్రతీ గురువారం సంత ఉండేది. నా క్లాస్మేట్లే కొంతమంది కూరలు అమ్మే వాళ్ళు ఆ సంతలో. వాళ్ళ దగ్గర కూరలు అవీ కొనడం కొంచెం వింతగా, ఇబ్బంద్ తోచేది. మేషారబ్బాయని - అడిగినా, అడగకపోయినా- ఇంకో నాలుగు పుంజీలు ఎక్కువ వేసేసేవాళ్ళు. ఇప్పటి పరిస్థితులేమో గాని, టీచర్లన్నా, వాళ్ళ పిల్లలన్నా బోల్డంత మర్యాద ఇచ్చేవారు పల్లెటూళ్ళలో అప్పట్లో. అందుకే "మహదేవు కృపన్ దేవుపల్లి దేవునిపల్లెయే".
