---
title: "తెలుగు పద్యానికి compiler?"
description: "భైరవభట్ల గారు, పద్యం.నెట్ మీద టపా రాసినప్పుడు, పద్యం.నెట్లో, (నాలాంటి) ఔత్సాహికులు పద్యాలు రాయప్రయత్నిస్తే, వ్యాకరణ పరంగా అవి సరియైనవా, లేక, వాటిలో తప్పులు ఏమైనా ఉన్నా..."
author: "Soma S Dhavala"
date: "2009-04-01"
categories: ["telugu", "archive", "పద్యాలు"]
---

భైరవభట్ల గారు, పద్యం.నెట్ మీద టపా రాసినప్పుడు,  
పద్యం.నెట్లో, (నాలాంటి) ఔత్సాహికులు పద్యాలు రాయప్రయత్నిస్తే, వ్యాకరణ పరంగా అవి సరియైనవా, లేక, వాటిలో తప్పులు ఏమైనా ఉన్నాయో గుర్తించి, సవరణలకి సూచనలు చేసే సౌలభ్యం ఉంటేబావుంటుంది  
అని వ్యాఖ్యరాద్దామనుకుంటూనే, మళ్ళే, ప్రతీ పద్యాన్ని పరీక్ష చెయ్యడం, ఎంత ఖాళీ సమయమున్నా కుదరకపోవచ్చని ఆగిపోయాను. మరి పరిష్కారమేంటి అని అలోచిస్తుండాగా ఇలాతోచింది. ఇది ఎంతవరకు సాధ్యమో (అసాధ్యంకాదు అని నా నమ్మకం) తెలుగు సాఫ్టువేరు జనులు చూడండి:  
తెలుగు పద్యానికి వ్యాకరణం ఉన్నాది. గణ విభజన, యతి-ప్రాస, మినహాయింపులు ఇత్యాదులు. ఇవన్నీ చూస్తే, తెలుగు పద్యానికి ఒక compiler ( lexicon analyzer + syntax analyzer మాత్రమే) తయారుచేయడం (మరీ)అంత కష్టంకాదనిపిస్తుంది,  
ఉదాహరణకి (laTeX ని అనుకరిస్తూ):  
\begin{ATaveladi}  
uppugappurambu nrokkapolikanunDu \\  
chooDachooDa ruchula jaaDa vaeraya \\  
purushulandu puNya purushulu vaeraya \\  
viSwadaabhiraama vinura vaema \\  
\end{ATaveladi}  
పై పద్యాన్ని, compile చేసిన తరువాత, ఆటవెలది లో ఉండాల్సిన గాణాలు లేవనో, ఒక వేళ యతి తప్పితే, ఏ పాదంలో తప్పిందో చెప్తూ, యతి-ప్రాస కుదిరే అక్షరాల్ని సూచించడం లాంటి పనులు సాఫ్టువేరు ద్వారా చేస్తే?  
వీటిలో అనుభం ఉన్నవారు, మీ అభిప్రాయాలని తెలియజేయండి. కష్టసాధ్యం కాదు అనుకుంటే, ప్రయత్నించవచ్చు కూడా! ఒకవేళ ఇలాంటి పరికరాలుంటే, నాకు సూచించగలరు.
