---
title: "134,217,726"
description: "The following article on chandassu was posted on telusA by Sri Prabhakar Vissavajjhala. The only changes"
author: "Soma S Dhavala"
date: "2010-09-27"
categories: ["telugu", "archive"]
---

The following article on chandassu was posted on telusA by Sri Prabhakar Vissavajjhala. The only changes  
made are to correct the typos pointed out by him in a subsequent mail -  
- Sri Ramakrishna Sanka (http://rksanka.tripod.com/)  
What is 'chandassu'? How is it framed? (confining to telugu language only)  
'chandassu' may be described as the one that designs the structural features of 'poetry'.  
If so what is 'poetry'?  
Poetry may be described as the 'mobilizing literature while itself keeps moving'. (kadalutoo, kadalincE saahityamE kavitvamu).  
Doesn't 'prose' move? Can't it mobilize?  
Sure it does. But, certainly not as gracefully, appealingly, memorably and aesthetically as 'poetry' does as everyone knows. It is easy to feel rather than to explain.  
What makes this difference? Is it 'chandassu'?  
'chandassu' only deals with the structural features of poetry. To be very specific it generates the 'rythm' of the 'literature' only. [Please ignore the term 'rhyme'in this context. Strictly speaking, 'rhyme' should be considered in figures of speeches (precisely, Sabdaalankaaraas) but not in 'chandassu'.] 'chandassu' should not be misunderstood as the representation of 'poetry' as many people tend to do so. chandassu is only a definable aspect of many definable and indefinable aspects of poetry.  
Why is 'rythm' so important for 'poetry'? Does that bring the initial beauty to 'literature'? Can't things exist without 'rythm' and still be beautiful?  
I wish people may not ask this question. For, the very existance of the universe itself is due to the 'rythmic' motion of the planets around the Sun. By the very rythmic rotation around itself and the Sun, the earth is resulting in the distinction of time into days, nights and years. If this rythm in the universe is absent/disturbed for any reason, the world may not make any sense. Even humans, for that matter all the living beings do keep maintaining rythms during the daily life as well as the life span (which are 'bilogical rythms'). Apparently, everything in the universe is rythmic, either in recognizable or unrecognizable manner. Coming to 'literature', even 'prose' is rythmic in an invisible manner due to grammar, without which a sentence becomes a haphazardous collection of words, which doesn't make any sense. However, this 'rythm' being very essential (sense-making oriented) is never considered as a 'rythm' at all. Probably, 'chandassu' may be described as a recognizable 'rythm' that is atributed to 'literature'.  
In essence, one can say one doesn't like a 'rythm' in particular, and it is unwise to say that rythm is unnecessary.  
Humans perceive information through the five 'senses' (vision, hearing, smell, taste and touch), which are assimilated by brain ultimately. It is often said that 'sarvEndriyaaNaam nayanam pradhaanam' (eye/vision is the best of all the senses.) However, there is nothing in the 'literature' to please the physical 'eye'. Literature is fundamentally perceived by listening or reading, where the 'ear' and subsequently the 'mind' play critical roles in understanding/appreciating it. Probably, due to inevitable situations in the past, where recitation was essential because of the lack of printing and copying facilities, it was more essential to make 'literature' more appealing by 'physical means'. So, as a matter of preliminary attraction, the strikingly rythmic patterns that aid the 'literature' are often very successful in catching the ears of the common public. As the 'rythmic literature' sounds like music, it can drag the attention of even the uninterested or the disinterested also at times and makes it long lasting in the minds too. However, a truly sensible, inquisitive, attentive, dedicated and probing soul always grasps the message equally from a non/less rythmic and a more rythmic literature in the same manner. Poetry, obviously, being much more than mere chandassu, as a matter of fact, with all its visibly flowing flair often stayed above'prose'in its appealing nature. (to be continued)  
With regards,  
Prabhakar Vissavajjhala  
Chandassu (2 of 3)  
How is 'chandassu' framed (in telugu)? How many types it is?  
'chandassu' is framed based on the number of 'aksharaas' (syllables) in each and every line (paada) of a poem. As the same lines are repeated (aavRtta), these are called 'vRttaas'. If all the lines in a poem follow the same 'types of aksharaas', it is called a 'sama vRtta'. There are 26 types of 'chandassu'.  
Before going into the deatils of them, what is an 'akshara'?  
There are two separate 'telugu' equivalents for English words 'letter' and 'syllable'. The first one is 'varNamu' (letter). This is the basic 'letter' of the language (telugu) in the alphabets, hence, the name 'varNa samaamnaayamu'. These are 56 in telugu. However, the equivalent for 'syllable' in telugu is 'aksharamu'. 'Syllable' is often defined as the 'unit of pronounciation at a stretch' with a collection of letters (varNaas) in it. However, there is a critical but practical difference in 'English' and 'telugu' here. In English at least on quite a few occasions, a syllable may be a 'word' (i.e., one syllable words, for eg., pen, gun, fun, fan, bill, kill, kick, chick, duck, pick etc.) hence, sense-making. But certainly not that often, an 'aksharamu' (syllable) can be 'sense- making' (word) in telugu. To my knowledge, 'Sree, stree, lE!, pO!, raa!,chee!' and a few others may be the only very few exceptions possible.  
Also, in telugu , every varNamu (letter) is an aksharamu (syllable), but every aksharamu can't be a varNamu. For eg. 'a, aa' are both varnaas and thereby aksharaas also. Whereas, in a word like 'svapnamu', 'sva' is an aksharamu (syllable), but not a varNamu (letter) as it has two 'varNaas' (sa and va) in it. These 'aksharaas' (syllables) are divided into 'laghuvu' and 'guruvu' based on the time period of pronounciation. (The scope of the discussion of 'laghuvu' and 'guruvu' distiction is beyond this article.) These 'aksharaas' (syallables, which very often don't make  
complete sense in telugu) are the fundamental aspects in designing the 'chandassu'.  
How many types of 'chandassu' are there?  
(chandassu of 'jaatulu and upajaatulu' of telugu literature is beyond the scope of this article. chandassu of 'vRttaas' is only touched upon here.)  
There are 26 types of chandassu. Each 'chandassu' is recognized by the number of 'aksharaas' present in each line of the poem. As an 'akshara' can be either a 'laghuvu' or a 'guruvu', the number of variations possible in each type of 'chandassu' follows a 'binary system'. The names /numbers of 'chandassu' and the numbers of 'sama vRttaas' that can be generated in each variety are as follows. _______________________________________________________________  
# of chandassu Name # of aksharaas # of sama vRttas  
per each line possible  
_______________________________________________________________  
1 ukta 1 2  
2 atyukta 2 4  
3 madhya 3 8  
4 pratisTha 4 16  
5 suprstisTha 5 32  
6 gaayatri 6 64  
7 ushTikku 7 128  
8 anusThuppu 8 256  
9 bRhati 9 512  
10 paMkti 10 1,024  
11 trishTuppu 11 2,048  
12 jagati 12 4,096  
13 atijagati 13 8,192  
14 Sakvari 14 16,384  
15 atiSakvari 15 32,768  
16 ashTi 16 65,536  
17 atyashTi 17 131,072  
18 dhRti 18 262,144  
19 atidhRti 19 524,288  
20 kRti 20 1,048,576  
21 prakRti 21 2,097,152  
22 aakRti 22 4,194,304  
23 vikRti 23 8,388,608  
24 sukRti 24 16,777,216  
25 abhikRti 25 33,554,432  
26 utkRti 26 67,108,864  
_____________________________________________________________  
Total # of sama vRttaas in 26 chandassus is 134,217,726  
_____________________________________________________________  
Source for the chart: 'sulakshaNa saaramu' by 'lingamagunTa timmakavi. Supposedly a contemporary of 'tenaali raamakRshNa, so belongs to 1550s or so.  
The amazing point is, inspite of the possible generation of millions of 'vRttaas' in 26 chandassus, the chandaah kartaas did not designate more than 200 vRttaas. The reason is anyone's guess.  
Not that all the combinations aksharaas will generate a specific rythm that suits a meaningful disposition of the 'language' to form the 'literature'. This truly requires a genius to designate which of these forms or patterns will suit that particular 'language' (telugu). It requires lots of thorough knowledge of the language and much more than that. Of course. it is not known, how and why a triplet akshara unit is considered to set a 'gaNa' to design the sequence of a chosen 'vRtta'.  
Inspite of 200 prescribed 'vRttaas', not more than 45-50 were regularly used in the various 'kaavyaas' over 1000 years of telugu literature.(to be continued)  
With regards,  
Prabhakar Vissavajjhala  
chandassu (3 of 3)  
List of sama vRttaas'  
________________________________________________________________________  
# of aksharaas Names of vRttaas gaNaas yati  
________________________________________________________________________  
8 vidyunmaala ma-ma-ga-ga 5  
bhadrakamu ra-sa-va ....  
10 maNi rangamu ra-sa-sa-ga 6  
11 indra vraja ta-ta-ja-ga-ga 8  
upEndra vraja ja-ta-ja-ga-ga 8  
rathOdhatamu ra-na-ra-va 7  
svaagatamu ra-na-bha-ga-ga 7  
tOvakamu bha-bha-bha-ga-ga 7  
12 bhujanga prayaatamu 4 ya 8  
indra vaMSamu ta-ta-ja-ra 8  
vamSastamu ja-ta-ja-ra 8  
sragviNi 4 ra 7  
druta vilambitamu na-bha-bha-ra 7  
tOTakamu 4 sa 9  
tOdakamu na-ja-ja-ya 8  
14 vana mayUramu bha-ja-sa-na-ga-ga 9  
vasanta tilaka ta-bha-ja-ja-ga-ga 8  
madana -------do---------- 9  
15 maalini na-na-ma-ya-ya 9  
sarasaamkamu sa-ja-sa-sa-ya 10  
sugandhi 7 ha-ga 9  
16 panca caamaramu ja-ra-ja-ra-ja-ga 10  
17 SikhriNi ya-ma-na-sa-bha-va 13  
pRdhvi ja-sa-ja-sa-ya-va 9/12  
mandaakraanta ma-bha-na-ta-ta-ga-ga 11  
18 matta kOkila ra-sa-ja-ja-bha-ra 11  
tarali bha-sa-na-ja-na-ra 11  
19 SaardUlamu ma-sa-ja-sa-ta-ta-ga 13  
taralamu na-bha-ra-sa-ja-ja-ga 12  
mEgha visphUrjitam ya-ma-na-sa-ra-ra-ga 13  
candrakaLa ra-sa-sa-ta-ja-ja-ga 11  
20 mattEbhamu sa-bha-ra-na-ma-ya-va 14  
utpalamaala bha-ra-na-bha-bha-ra-va 10  
amburuhamu bha-bha-bha-bha-ra-sa-va 13  
21 campaka maala na-ja-bha-ja-ja-ja-ra 11  
sragdhara ma-ra-bha-na-ya-ya-ya 8,15  
22 mahaa sragdhara sa-ta-ta-na-sa-ra-ra-ga 9,16  
maanini 7 bha-ga 7, 13, 19  
taraLamu 7 na-ga 13  
23 kaviraaja viraajitam na-6 ja-va 8, 14, 20  
24 kraUnca pada bha-ma-sa-bha-na-na-na-ya 11, 19  
25 saadhvi bha-na-ja-na-sa-na-na-bha-ga8, 15, 22  
26 prabhu 3 na-5 ja-va 9, 15, 21  
malayajamu na-ja-na-sa-na-na-bha-na-va 8, 15, 22  
mangaLa mahaaSree bha-ja-sa-na-bha-ja-sa-na-ga-ga 9, 17  
______________________________________________________________________  
In addition to the above 45, there are 5 more frequently used vRttaas.  
______________________________________________________________________  
27 laakshaNee vRtta bha-na-na-na-na-bha-na-na-sa 16  
29 ramaNaka vRtta 9 na-va 9,17,25  
30 layagraahi bha-ja-sa-na-bha-ja-sa-na-bha-ya  
praasa yati at 9,18,27  
34 layavibhaati na-sa-na-na-sa-na-na-sa-na-na-sa-ga  
praasa yati at 10,20,30  
danDakamu sa-na-ha- n(ta)--------ga or  
n(ta)--------------------ga  
All of it is considered as one 'paada'  
without praasa and yati  
_______________________________________________________________________  
Merits and demerits of 'vRtta chandassu':  
While compilation of tremendous 'poetic'literature is the major merit, the usage of 'vyardha padaas' to suit 'chandassu' (filler words) is the major demerit. While 'chandO haters' try to 'overplay' this aspect, 'chandO lovers' overlook this. Keeping this unresolvable issue aside, one got to accept that amazing skills of composing 'poetry' were evident on quite a few occasions in the telugu literature, where unparallel talents were brought into existance to express human feelings comprising of 'nava rasaas'.  
While 'chandO haters' think that 'gaNa' oriented 'vRtta' chandassu is a hurdle, the 'chandO lovers' feel that as a 'cherishable challenge'. While creating rythm in the literature is the major function of 'chandassu', a maatraa chandassu, that is not bound by any 'sequences of gaNaas' can also be rythmic, which is also chandassu. However, it is unfortunate that both the'chandO haters' and 'chandO lovers' totally ignore this aspect very often.  
By all means, 'chandassu' should aid and enhance the beauty of the 'language' and 'literature' as an undercurrent. Poetry (not chandassu) should reflect the brilliance and elegance of the poet, but not his/her labour in creating poetry. Afterall, poetry is for 'appealing', so it shouldn't created in an 'appaling' manner.  
With regards,  
Prabhakar Vissavajjhala  
Note: The above text is copied from Ramakrishna Sanka (http://rksanka.tripod.com/). I am afraid that if those tripod sites are down, then we may loose this information. How do we explain what is chandassu to non-telugu speaking people and that poetic meter exists in telugu too.
