---
title: "పద్యపుష్పోపహారము"
description: "శ్రీముఖ వ్యాసపౌర్ణమి శ్రీరస్తు, శ్రీమత్పరదేవతాయైనమః బ్రహ్మశ్రీ వేదమూర్తులు, బ్రహ్మనిష్ఠులు, తపస్సంపన్నులు, శ్రీ ధవళ శ్రీరామావధాని మహోదయులకు, వారి సహస్రచంద్ర దర్శన మహోత..."
author: "Soma S Dhavala"
date: "2011-04-14"
categories: ["telugu", "archive"]
---

శ్రీముఖ వ్యాసపౌర్ణమి  
తేదీ 3-7-1993  
శ్రీరస్తు, శ్రీమత్పరదేవతాయైనమః  
బ్రహ్మశ్రీ వేదమూర్తులు, బ్రహ్మనిష్ఠులు, తపస్సంపన్నులు, శ్రీ ధవళ శ్రీరామావధాని మహోదయులకు, వారి సహస్రచంద్ర దర్శన మహోత్సవ సందర్భమున సమర్పించిన పద్యపుష్పోపహారము  
శా||  
శ్రీవాణీహిమవద్గిరీంద్రతనయాసీమంతినుల్ ప్రేమనెం  
తే వక్షోముఖపార్శ్వ భాగములయం దేపారగా నొప్పు నా  
శ్రీ వైకుంఠవిధీందుశేఖరులు పేర్మిన్ బ్రోచుతున్ వేదవి  
ద్యావాచస్పతి నీ బుధున్ ధవళ వంశాంభోధి రాకాశశిన్  
సీ||  
ఏబదేండ్లకు మున్నె యెంతయు భక్తితో  
జంద్రశేఖర యతిస్వామి విమల  
పాదపద్మమ్ములు స్వాంతమ్మునన్ నిల్పి  
యర్చించునట్టి పుణ్యాత్మకుండు;  
శంకరమఠము విజయనగరంబున  
నెలకొల్పినట్టి ధన్యులను మిన్న  
వేదమూర్తియు, శ్రౌతవిద్యావివేకియు,  
మంత్రమూర్తియునైన మాన్యతముడు  
గీ||  
ప్రేమతోడుత నన్ను నెవ్వేళగాంచు  
నట్టి మామక మాతులు ననవరతము  
గొలుతు సధ్బక్తి గురుమూర్తి నలఘుయశుని  
ధవళ వంశ్యు శ్రీరామావధాని, ననఘు  
శా||  
వేదోపాసనచే బవిత్రులయి సద్విఖ్యాతి నార్జించుటే  
కా దెన్నోక్రతువుల్ పొనర్చి త్రిదివాగ్రస్వాస్థ్యముం గాంచి రెం  
తే దాతల్ మఱితండ్రు; లాసరణినట్లే పూని మీ వంశమ  
ర్యాదని నిల్పితి, రీవు నీయనుజు లార్యా! రామనామాంకితా!  
చం||  
ఎనుబదినాలుగేండ్లు చనియెన్ గడులెస్సగ; వేదపూరుషుం  
డనియె శతాయువంచు; నటులౌటగొఱంత యెకింతలేక నీ  
వనఘ! శతాయురున్నతి, ననామయభాగ్యముగాంచి, సత్తపో  
ధనము గడించి మించుమ, నితాంత యశోనిధివై సుఖింపుమా!  
చం||  
పరమకృపావతారుడయి భవ్యతపోనిధియైన చంద్రశే  
ఖరయతిసార్వభౌముల యఖండకృపారస మెల్లవేళదా  
బరగగనీపయిన్, సకలభద్రములన్ గని, యస్మదాదులం  
దఱకిని మార్గదర్శివయి, ధన్యులజేయుమి వేదవిద్వరా!  
ఇట్లు,  
వినీతుడు, మధురకవి  
అనిపిండి వరాహనరసింహమూర్తి  
విజయనగరము
