---
title: "చ‘తురంగ’గతి బంధ కందము"
description: "చ‘తురంగ’గతి బంధ కందము రాయాలంటే, ముందు సర్వలఘుకందం ఒక్కటైనా రాయాలని, నిన్న ఒకటి రాసాను. ఆంధ్రామృతం బ్లాగులో మొదటగా చూసిన చ‘తురంగ’గతి బంధ కందము ప్రయత్నిద్దామని సంకల్పిచా..."
author: "Soma S Dhavala"
date: "2010-08-25"
categories: ["telugu", "archive", "పద్యాలు"]
---

చ‘తురంగ’గతి బంధ కందము రాయాలంటే, ముందు సర్వలఘుకందం ఒక్కటైనా రాయాలని, నిన్న ఒకటి రాసాను. ఆంధ్రామృతం బ్లాగులో మొదటగా చూసిన చ‘తురంగ’గతి బంధ కందము ప్రయత్నిద్దామని సంకల్పిచాను. కాకపోతే ఆచార్య చింతా రామకృష్ణారావుగారు చేసిన ప్రయోగం కొంచం కష్టమనిపించి, సరళమైన విధంగా, paved road మీద తురగగమనం సాగింది.  
కం||  
కలువ తళుకుబెళుకుల చెలి  
యల కులుకులొలుకు కనులవియగు జిగిబిగి సొం  
పుల శృతిలయగతులు వలపు  
గొలుసులు ముడిపడి అలజడి గొలిపె నిలకడన్  
8 x 8 పట్టికలో అమరిస్తే  
క లు వ తళు కు బె ళు  
కు ల చె లియ ల కు లు  
కు లొ లు కుక ను ల వి  
య గు జి గిబి గి సొ ౦  
పు ల శృ తిల య గ తు  
లు వ ల పు  
గొ లు సు లు  
ము డి ప డిఅ ల జ డి  
గొ లి పె నిల క డ న్  
చ‘తురంగ’గతి బంధం కావించబడ్డ వాక్యం "కలువచెలియకనులసొగసులు". చదరంగం బోర్డులో గుఱ్ఱం నడక, మొదటి గడి top,left corner (r1,c1) లో మొదలయ్యి రెండు అడ్డం (ఎడమనుంచి, కుడికి) ఒక నిలువు, ఇలా సాగింది. ఈ నడకలో సౌలభ్యం , ప్రతి మూడు అక్షరాలు ఏలాగూ ఒక అర్ధం వచ్చే వరుసలోనే ఉంటాయి. ఉదాహరణకి, చెలియ. ఇందులో ఉన్న మరో విశేషం, (r1 c1) దగ్గర మొదలైతే, (r6,c8) దగ్గర బోర్డు బయటకి వచ్చేస్తాం అంతరాయం లేకుండగా. అలాకాకండా, రెండు నిలువు, ఒక అడ్డం వేసినప్పుడు, వాక్యనిర్మాణం కొంచం క్లిష్టతరం అవుతుంది. మరొక విషయం, రెండవ పాదంలో, చివరి అక్షరం "సొం" ని "సొ + ం" గా విడగొట్టడం జరిగింది. ఇది సర్వలఘు కందం అవుతుందో అవదో తెలియదు మరి. అంటే, "డన్ = డ + న్" కి ఇచ్చిన exception, ఇక్కడకూడా వర్తిస్తుందా మరి? వర్తిస్తుందనే అనుకుంటున్నాను.
