---
title: "ఇదేనండి ఇదేనండి భాగ్యనగరము - తెరవెనుక పాట"
description: "జె.వి. రమణమూర్తి గారు \"కన్యాశుల్కం\" నాటికాన్ని (ఇప్పటికీ) ఒక యజ్ఞం లా నిర్వహిస్తున్న సోమయాజి. రంగస్థలంపై ఆయన అనుభవం 64 సంవత్సరాలు. ఆయన్ని \"హ్యూస్టన్ లో నెలనెలావెన్నెల\"..."
author: "Soma S Dhavala"
date: "2010-08-22"
categories: ["telugu", "archive", "సినీమా"]
---

జె.వి. రమణమూర్తి గారు "కన్యాశుల్కం" నాటికాన్ని (ఇప్పటికీ) ఒక యజ్ఞం లా నిర్వహిస్తున్న సోమయాజి. రంగస్థలంపై ఆయన అనుభవం 64 సంవత్సరాలు. ఆయన్ని "హ్యూస్టన్ లో నెలనెలావెన్నెల" లో భాగంగా కలిసే అదృష్టం కలిగింది. ఆయన తన సినీ రంగ ప్రవేశం గురించి వివరిస్తూ*  
"....నా సినిమా ప్రవేశానికి ప్రధానకారణం "కాళరాత్రి" అనే నాటకం. ఈ నాటక ప్రదర్శనని హైదరాబాదులో చూసిన కొంతమంది సినీ ప్రముఖులు, నన్ను సినిమాల్లో ప్రయత్నించ వలసింది గా కోరారు. అలా ఎల్.వి. ప్రసాద్ గారు మొదటి సినిమా కోసం పిలిచినా, వారి మేనల్లుడు తిలక్ దర్శకత్వంలోనే మొదట నటించే అవకాశం వచ్చింది. అదే ఎమ్.ఎల్.ఏ చిత్రం. అవుట్ డోర్ చిత్రీకరణకోసం చిత్రబృందం కాశ్మీర్ అని, ఊటీ అని, తర్జన భర్జనలు పడుతుండగా, మీకు హైదరాబాద్ అనే ఊరుంది తెలుసా అనేసరికి, సభ్యులందరూ కాసేపు విస్తుపోయి -నిజమే కదూ అనుకుంటూ - అవుట్ డోర్ కోసం హైదరాబాద్ ని ఎన్నుకున్నారు. అప్పట్లో హైదరాబాదు ఎంతో రమణీయంగా ఉండేది. ఇక్కడి ప్రతీ వీధి, ఢిల్లీ పార్లమెంట్ రోడ్ అంత సుందరంగా ఉండేది.....  
.. ఏ ప్రదేశం చూసినా సుందరంగా ఉండడం వలన, అలా నాలుగు కార్లలో వెళ్ళి, ఎక్కడంటే అక్కడ ఆగి, కావాల్సిన సీన్స్ - అనుకున్నవి, అనుకోనివి - తీసుకునేవాళ్లం. ఇవన్నీ ఎందుకయ్యా అని తిలక్ ని అడిగితే, చెప్తానుండు అని వాటిని ఒక 600 అడుగులకి కుదించి, కూర్చి, ఆరుద్ర గారిని పిలిచి ఈ దృశ్యమాలిక కి సరిపోయేవిధంగా ఒక పాటరాయమన్నారు. ఆవిధంగా ఇదేనండి, ఇదేనండి భాగ్యనగరము పాట పుట్టింది...."  
అంటూ మరెన్నో విషయాల గురించి కూడా మాట్లాడారు. వీడియో లభ్యమైనప్పుడు లింక్ పోస్ట్ చేస్తాను.  
చిక్కగా రాసే ఒక కలం కూడా ఇదేనండి, ఇదేనండి భాగ్యనగరము పాటపై ఒక ఊహాగానం చేసింది. విని ఆనందించండి.  
* భావం మాత్రమే. యథాతథం కాదు.
